// SPDX-License-Identifier: GPL-3.0-only

package com.meshcoretwo.android.ui.theme

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

// Full Material3 ColorScheme for each of the 4 non-Default built-in themes (Aurora, Sunrise,
// Graphite, Ultraviolet). The palettes are original to this app — no third-party color set is
// used. Each scheme was generated the same way Color.kt's Default palette was: Material
// color-utilities "Fidelity" scheme variant (contrast level 0, spec "2021" — the 35-role set
// `androidx.compose.material3.ColorScheme` takes), seeded from the theme's accent — the light
// accent for the light scheme, the dark accent for the dark scheme. Computed offline with the
// `materialyoucolor` Python port; ships as baked constants only, no generation code or new
// dependency in the app itself.
//
// `background`/`surface` are then overridden with the theme's canvas hex (see `Theme.surfaces`), so
// the tinted canvas the theme paints matches the Material roles that default to it. Every other
// role stays exactly as generated. `onBackground`/`onSurface` keep their generated values, which
// clear WCAG AA against the canvases used here (`ThemeContrastTest` guards this).

// aurora
val AuroraLightColors = lightColorScheme(
    primary = Color(0xFF005F59),
    onPrimary = Color(0xFFFFFFFF),
    primaryContainer = Color(0xFF0B7A72),
    onPrimaryContainer = Color(0xFFACFFF5),
    inversePrimary = Color(0xFF7CD6CC),
    secondary = Color(0xFF446460),
    onSecondary = Color(0xFFFFFFFF),
    secondaryContainer = Color(0xFFC7EAE4),
    onSecondaryContainer = Color(0xFF4A6A66),
    tertiary = Color(0xFF834327),
    onTertiary = Color(0xFFFFFFFF),
    tertiaryContainer = Color(0xFFA15A3C),
    onTertiaryContainer = Color(0xFFFFECE6),
    background = Color(0xFFF0F8F7),
    onBackground = Color(0xFF181C1C),
    surface = Color(0xFFF0F8F7),
    onSurface = Color(0xFF181C1C),
    surfaceVariant = Color(0xFFD9E5E2),
    onSurfaceVariant = Color(0xFF3E4947),
    surfaceTint = Color(0xFF006A63),
    inverseSurface = Color(0xFF2D3130),
    inverseOnSurface = Color(0xFFEEF2F0),
    error = Color(0xFFBA1A1A),
    onError = Color(0xFFFFFFFF),
    errorContainer = Color(0xFFFFDAD6),
    onErrorContainer = Color(0xFF93000A),
    outline = Color(0xFF6E7977),
    outlineVariant = Color(0xFFBDC9C6),
    scrim = Color(0xFF000000),
    surfaceBright = Color(0xFFF6FAF8),
    surfaceDim = Color(0xFFD7DBD9),
    surfaceContainer = Color(0xFFEBEFED),
    surfaceContainerHigh = Color(0xFFE5E9E7),
    surfaceContainerHighest = Color(0xFFDFE3E2),
    surfaceContainerLow = Color(0xFFF1F4F3),
    surfaceContainerLowest = Color(0xFFFFFFFF),
)

val AuroraDarkColors = darkColorScheme(
    primary = Color(0xFF71FDEC),
    onPrimary = Color(0xFF003732),
    primaryContainer = Color(0xFF4FE0D0),
    onPrimaryContainer = Color(0xFF006058),
    inversePrimary = Color(0xFF006A61),
    secondary = Color(0xFF9FD0C8),
    onSecondary = Color(0xFF003732),
    secondaryContainer = Color(0xFF20514B),
    onSecondaryContainer = Color(0xFF91C2BA),
    tertiary = Color(0xFFFFE2BF),
    onTertiary = Color(0xFF452B00),
    tertiaryContainer = Color(0xFFFFBF61),
    onTertiaryContainer = Color(0xFF764D00),
    background = Color(0xFF071416),
    onBackground = Color(0xFFDDE4E1),
    surface = Color(0xFF071416),
    onSurface = Color(0xFFDDE4E1),
    surfaceVariant = Color(0xFF3C4947),
    onSurfaceVariant = Color(0xFFBBCAC6),
    surfaceTint = Color(0xFF49DBCC),
    inverseSurface = Color(0xFFDDE4E1),
    inverseOnSurface = Color(0xFF2B3230),
    error = Color(0xFFFFB4AB),
    onError = Color(0xFF690005),
    errorContainer = Color(0xFF93000A),
    onErrorContainer = Color(0xFFFFDAD6),
    outline = Color(0xFF859491),
    outlineVariant = Color(0xFF3C4947),
    scrim = Color(0xFF000000),
    surfaceBright = Color(0xFF343B39),
    surfaceDim = Color(0xFF0E1514),
    surfaceContainer = Color(0xFF1A2120),
    surfaceContainerHigh = Color(0xFF252B2A),
    surfaceContainerHighest = Color(0xFF2F3635),
    surfaceContainerLow = Color(0xFF161D1C),
    surfaceContainerLowest = Color(0xFF090F0E),
)

// sunrise
val SunriseLightColors = lightColorScheme(
    primary = Color(0xFFA62301),
    onPrimary = Color(0xFFFFFFFF),
    primaryContainer = Color(0xFFC93C1A),
    onPrimaryContainer = Color(0xFFFFEFEC),
    inversePrimary = Color(0xFFFFB4A3),
    secondary = Color(0xFF974633),
    onSecondary = Color(0xFFFFFFFF),
    secondaryContainer = Color(0xFFFF987F),
    onSecondaryContainer = Color(0xFF772E1D),
    tertiary = Color(0xFF00579E),
    onTertiary = Color(0xFFFFFFFF),
    tertiaryContainer = Color(0xFF0070C8),
    onTertiaryContainer = Color(0xFFEEF3FF),
    background = Color(0xFFFFF6EF),
    onBackground = Color(0xFF261815),
    surface = Color(0xFFFFF6EF),
    onSurface = Color(0xFF261815),
    surfaceVariant = Color(0xFFFFDAD2),
    onSurfaceVariant = Color(0xFF5A413B),
    surfaceTint = Color(0xFFB22C09),
    inverseSurface = Color(0xFF3D2D29),
    inverseOnSurface = Color(0xFFFFEDE9),
    error = Color(0xFFBA1A1A),
    onError = Color(0xFFFFFFFF),
    errorContainer = Color(0xFFFFDAD6),
    onErrorContainer = Color(0xFF93000A),
    outline = Color(0xFF8E7069),
    outlineVariant = Color(0xFFE2BFB6),
    scrim = Color(0xFF000000),
    surfaceBright = Color(0xFFFFF8F6),
    surfaceDim = Color(0xFFEFD4CE),
    surfaceContainer = Color(0xFFFFE9E4),
    surfaceContainerHigh = Color(0xFFFEE2DC),
    surfaceContainerHighest = Color(0xFFF8DDD7),
    surfaceContainerLow = Color(0xFFFFF0ED),
    surfaceContainerLowest = Color(0xFFFFFFFF),
)

val SunriseDarkColors = darkColorScheme(
    primary = Color(0xFFFFB59F),
    onPrimary = Color(0xFF5E1600),
    primaryContainer = Color(0xFFFF8A66),
    onPrimaryContainer = Color(0xFF752306),
    inversePrimary = Color(0xFF9F4123),
    secondary = Color(0xFFF9B7A4),
    onSecondary = Color(0xFF4E2518),
    secondaryContainer = Color(0xFF6B3D2F),
    onSecondaryContainer = Color(0xFFE9A996),
    tertiary = Color(0xFF44DCCA),
    onTertiary = Color(0xFF003732),
    tertiaryContainer = Color(0xFF00BFAE),
    onTertiaryContainer = Color(0xFF004740),
    background = Color(0xFF1A0F12),
    onBackground = Color(0xFFF2DED9),
    surface = Color(0xFF1A0F12),
    onSurface = Color(0xFFF2DED9),
    surfaceVariant = Color(0xFF56423C),
    onSurfaceVariant = Color(0xFFDDC0B9),
    surfaceTint = Color(0xFFFFB59F),
    inverseSurface = Color(0xFFF2DED9),
    inverseOnSurface = Color(0xFF392E2B),
    error = Color(0xFFFFB4AB),
    onError = Color(0xFF690005),
    errorContainer = Color(0xFF93000A),
    onErrorContainer = Color(0xFFFFDAD6),
    outline = Color(0xFFA48B84),
    outlineVariant = Color(0xFF56423C),
    scrim = Color(0xFF000000),
    surfaceBright = Color(0xFF423733),
    surfaceDim = Color(0xFF1A110E),
    surfaceContainer = Color(0xFF271D1A),
    surfaceContainerHigh = Color(0xFF322724),
    surfaceContainerHighest = Color(0xFF3E322F),
    surfaceContainerLow = Color(0xFF231916),
    surfaceContainerLowest = Color(0xFF150C09),
)

// graphite
val GraphiteLightColors = lightColorScheme(
    primary = Color(0xFF020204),
    onPrimary = Color(0xFFFFFFFF),
    primaryContainer = Color(0xFF1C1C22),
    onPrimaryContainer = Color(0xFF85848B),
    inversePrimary = Color(0xFFC8C5CD),
    secondary = Color(0xFF5F5E61),
    onSecondary = Color(0xFFFFFFFF),
    secondaryContainer = Color(0xFFE5E1E5),
    onSecondaryContainer = Color(0xFF656467),
    tertiary = Color(0xFF030200),
    onTertiary = Color(0xFFFFFFFF),
    tertiaryContainer = Color(0xFF201C13),
    onTertiaryContainer = Color(0xFF8B8477),
    background = Color(0xFFF4F4F5),
    onBackground = Color(0xFF1C1B1C),
    surface = Color(0xFFF4F4F5),
    onSurface = Color(0xFF1C1B1C),
    surfaceVariant = Color(0xFFE4E1E7),
    onSurfaceVariant = Color(0xFF47464B),
    surfaceTint = Color(0xFF5E5E65),
    inverseSurface = Color(0xFF313031),
    inverseOnSurface = Color(0xFFF4F0F0),
    error = Color(0xFFBA1A1A),
    onError = Color(0xFFFFFFFF),
    errorContainer = Color(0xFFFFDAD6),
    onErrorContainer = Color(0xFF93000A),
    outline = Color(0xFF78767B),
    outlineVariant = Color(0xFFC8C5CB),
    scrim = Color(0xFF000000),
    surfaceBright = Color(0xFFFCF8F8),
    surfaceDim = Color(0xFFDDD9D9),
    surfaceContainer = Color(0xFFF1EDED),
    surfaceContainerHigh = Color(0xFFEBE7E7),
    surfaceContainerHighest = Color(0xFFE5E2E2),
    surfaceContainerLow = Color(0xFFF7F3F3),
    surfaceContainerLowest = Color(0xFFFFFFFF),
)

val GraphiteDarkColors = darkColorScheme(
    primary = Color(0xFFFFFFFF),
    onPrimary = Color(0xFF2F3133),
    primaryContainer = Color(0xFFE2E2E5),
    onPrimaryContainer = Color(0xFF636467),
    inversePrimary = Color(0xFF5D5E61),
    secondary = Color(0xFFC8C6C7),
    onSecondary = Color(0xFF303031),
    secondaryContainer = Color(0xFF49494A),
    onSecondaryContainer = Color(0xFFB9B8B9),
    tertiary = Color(0xFFFFFFFF),
    onTertiary = Color(0xFF352F2B),
    tertiaryContainer = Color(0xFFEBE0DA),
    onTertiaryContainer = Color(0xFF6A635E),
    background = Color(0xFF000000),
    onBackground = Color(0xFFE5E2E1),
    surface = Color(0xFF000000),
    onSurface = Color(0xFFE5E2E1),
    surfaceVariant = Color(0xFF45474A),
    onSurfaceVariant = Color(0xFFC5C6CA),
    surfaceTint = Color(0xFFC6C6C9),
    inverseSurface = Color(0xFFE5E2E1),
    inverseOnSurface = Color(0xFF313030),
    error = Color(0xFFFFB4AB),
    onError = Color(0xFF690005),
    errorContainer = Color(0xFF93000A),
    onErrorContainer = Color(0xFFFFDAD6),
    outline = Color(0xFF8F9194),
    outlineVariant = Color(0xFF45474A),
    scrim = Color(0xFF000000),
    surfaceBright = Color(0xFF3A3939),
    surfaceDim = Color(0xFF141313),
    surfaceContainer = Color(0xFF201F20),
    surfaceContainerHigh = Color(0xFF2A2A2A),
    surfaceContainerHighest = Color(0xFF353435),
    surfaceContainerLow = Color(0xFF1C1B1C),
    surfaceContainerLowest = Color(0xFF0E0E0E),
)

// ultraviolet
val UltravioletLightColors = lightColorScheme(
    primary = Color(0xFF512AE6),
    onPrimary = Color(0xFFFFFFFF),
    primaryContainer = Color(0xFF6A4CFF),
    onPrimaryContainer = Color(0xFFF4EFFF),
    inversePrimary = Color(0xFFC8BFFF),
    secondary = Color(0xFF5E53A5),
    onSecondary = Color(0xFFFFFFFF),
    secondaryContainer = Color(0xFFB1A6FE),
    onSecondaryContainer = Color(0xFF423788),
    tertiary = Color(0xFF8F3D00),
    onTertiary = Color(0xFFFFFFFF),
    tertiaryContainer = Color(0xFFB54F00),
    onTertiaryContainer = Color(0xFFFFEDE6),
    background = Color(0xFFF5F2FF),
    onBackground = Color(0xFF1C1A24),
    surface = Color(0xFFF5F2FF),
    onSurface = Color(0xFF1C1A24),
    surfaceVariant = Color(0xFFE5DFF5),
    onSurfaceVariant = Color(0xFF474556),
    surfaceTint = Color(0xFF5A38EF),
    inverseSurface = Color(0xFF312F3A),
    inverseOnSurface = Color(0xFFF4EEFD),
    error = Color(0xFFBA1A1A),
    onError = Color(0xFFFFFFFF),
    errorContainer = Color(0xFFFFDAD6),
    onErrorContainer = Color(0xFF93000A),
    outline = Color(0xFF787588),
    outlineVariant = Color(0xFFC9C4D9),
    scrim = Color(0xFF000000),
    surfaceBright = Color(0xFFFCF8FF),
    surfaceDim = Color(0xFFDDD8E6),
    surfaceContainer = Color(0xFFF1ECFA),
    surfaceContainerHigh = Color(0xFFEBE6F4),
    surfaceContainerHighest = Color(0xFFE5E0EF),
    surfaceContainerLow = Color(0xFFF7F1FF),
    surfaceContainerLowest = Color(0xFFFFFFFF),
)

val UltravioletDarkColors = darkColorScheme(
    primary = Color(0xFFC8BFFF),
    onPrimary = Color(0xFF2F1D7D),
    primaryContainer = Color(0xFFA99BFF),
    onPrimaryContainer = Color(0xFF3C2D8B),
    inversePrimary = Color(0xFF5E50AE),
    secondary = Color(0xFFC9C1ED),
    onSecondary = Color(0xFF312C4F),
    secondaryContainer = Color(0xFF474267),
    onSecondaryContainer = Color(0xFFB7B0DB),
    tertiary = Color(0xFFDAC842),
    onTertiary = Color(0xFF373100),
    tertiaryContainer = Color(0xFFBAA923),
    onTertiaryContainer = Color(0xFF453D00),
    background = Color(0xFF0C0A1C),
    onBackground = Color(0xFFE5E1E9),
    surface = Color(0xFF0C0A1C),
    onSurface = Color(0xFFE5E1E9),
    surfaceVariant = Color(0xFF484552),
    onSurfaceVariant = Color(0xFFC9C4D3),
    surfaceTint = Color(0xFFC8BFFF),
    inverseSurface = Color(0xFFE5E1E9),
    inverseOnSurface = Color(0xFF312F36),
    error = Color(0xFFFFB4AB),
    onError = Color(0xFF690005),
    errorContainer = Color(0xFF93000A),
    onErrorContainer = Color(0xFFFFDAD6),
    outline = Color(0xFF928F9D),
    outlineVariant = Color(0xFF484552),
    scrim = Color(0xFF000000),
    surfaceBright = Color(0xFF3A383F),
    surfaceDim = Color(0xFF141319),
    surfaceContainer = Color(0xFF201F25),
    surfaceContainerHigh = Color(0xFF2B2930),
    surfaceContainerHighest = Color(0xFF35343A),
    surfaceContainerLow = Color(0xFF1C1B21),
    surfaceContainerLowest = Color(0xFF0E0D13),
)
