// SPDX-License-Identifier: GPL-3.0-only

package com.meshcoretwo.android.ui.theme

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

// Full Material3 ColorScheme for each of the 9 non-Default built-in themes (Ember, Fern, Marine,
// Olive, Lavender, Sakura, Solarized, Nord, Catppuccin), generated the same way Color.kt's Default
// palette was in Phase 6 slice 2: Material color-utilities "Fidelity" scheme variant (contrast
// level 0, spec "2021" — the pre-"Expressive" 35-role set `androidx.compose.material3.ColorScheme`
// takes), seeded per theme from `Theme.<id>.accentColor` (iOS `Theme.swift`) — the light seed for
// the light scheme, the dark seed for the dark scheme, since (unlike Default's single non-adaptive
// accent) most of these themes carry distinct light/dark accent asset values on iOS. Computed
// offline with the `materialyoucolor` Python port, same tool and method as slice 2; ships as
// baked constants only, no generation code or new dependency in the app itself.
//
// `background`/`surface` are then overridden with the theme's literal `surfaces.canvas` hex from
// `Theme.swift` (light/dark values read from the iOS asset catalog,
// `MC1/Resources/Assets.xcassets/Theme/<Name>/Canvas.colorset`) — the "seed = accent, surfaces
// поверх" design decision from PLAN.md's Phase 6 slice 3 entry: `canvas` is the one surface iOS
// itself paints uniformly (`.themedCanvas`), so it replaces the generated tonal background/surface
// role outright rather than blending into the tonal palette. Every other role (including
// `surfaceVariant`, which will carry the `card` tier once Phase 6 slice 5 builds the shared card
// component) stays exactly as Fidelity generated it. `onBackground`/`onSurface` are kept at their
// generated values rather than recomputed against the literal canvas override — verified offline
// (script, not committed) to clear WCAG AA 4.5:1 against every theme's actual canvas in the
// appearance it actually renders in (Ember is forced dark, so only its dark scheme was checked;
// its unused light scheme does not clear AA against forced black, which is expected and harmless).
// Ember has no `card` tier (`Theme.ember.surfaces.card == nil`), so its `surfaceVariant` is left
// fully generated, matching every other un-overridden role.
//
// Naming mirrors Color.kt's Default palette (`md_theme_<mode>_<role>`) with the theme id inserted:
// `md_theme_<id>_<mode>_<role>`. Kept `private` — only this file's `<Theme>LightColors`/
// `<Theme>DarkColors` vals below and `ThemeRegistry.kt`'s `Theme` instances need them.

// ember
private val md_theme_ember_light_primary = Color(0xFF910009)
private val md_theme_ember_light_onPrimary = Color(0xFFFFFFFF)
private val md_theme_ember_light_primaryContainer = Color(0xFFB81A1A)
private val md_theme_ember_light_onPrimaryContainer = Color(0xFFFFCBC4)
private val md_theme_ember_light_inversePrimary = Color(0xFFFFB4AB)
private val md_theme_ember_light_secondary = Color(0xFFA03F36)
private val md_theme_ember_light_onSecondary = Color(0xFFFFFFFF)
private val md_theme_ember_light_secondaryContainer = Color(0xFFFD867A)
private val md_theme_ember_light_onSecondaryContainer = Color(0xFF741F19)
private val md_theme_ember_light_tertiary = Color(0xFF004683)
private val md_theme_ember_light_onTertiary = Color(0xFFFFFFFF)
private val md_theme_ember_light_tertiaryContainer = Color(0xFF005EAC)
private val md_theme_ember_light_onTertiaryContainer = Color(0xFFC1D8FF)
private val md_theme_ember_light_background = Color(0xFF000000)
private val md_theme_ember_light_onBackground = Color(0xFF271816)
private val md_theme_ember_light_surface = Color(0xFF000000)
private val md_theme_ember_light_onSurface = Color(0xFF271816)
private val md_theme_ember_light_surfaceVariant = Color(0xFFFFDAD6)
private val md_theme_ember_light_onSurfaceVariant = Color(0xFF5B403D)
private val md_theme_ember_light_surfaceTint = Color(0xFFB91B1B)
private val md_theme_ember_light_inverseSurface = Color(0xFF3E2C2A)
private val md_theme_ember_light_inverseOnSurface = Color(0xFFFFEDEA)
private val md_theme_ember_light_error = Color(0xFFBA1A1A)
private val md_theme_ember_light_onError = Color(0xFFFFFFFF)
private val md_theme_ember_light_errorContainer = Color(0xFFFFDAD6)
private val md_theme_ember_light_onErrorContainer = Color(0xFF93000A)
private val md_theme_ember_light_outline = Color(0xFF8F6F6C)
private val md_theme_ember_light_outlineVariant = Color(0xFFE4BEB9)
private val md_theme_ember_light_scrim = Color(0xFF000000)
private val md_theme_ember_light_surfaceBright = Color(0xFFFFF8F7)
private val md_theme_ember_light_surfaceDim = Color(0xFFF1D3D0)
private val md_theme_ember_light_surfaceContainer = Color(0xFFFFE9E6)
private val md_theme_ember_light_surfaceContainerHigh = Color(0xFFFFE2DE)
private val md_theme_ember_light_surfaceContainerHighest = Color(0xFFFADCD8)
private val md_theme_ember_light_surfaceContainerLow = Color(0xFFFFF0EE)
private val md_theme_ember_light_surfaceContainerLowest = Color(0xFFFFFFFF)
private val md_theme_ember_dark_primary = Color(0xFFFFB4AB)
private val md_theme_ember_dark_onPrimary = Color(0xFF690005)
private val md_theme_ember_dark_primaryContainer = Color(0xFFB81A1A)
private val md_theme_ember_dark_onPrimaryContainer = Color(0xFFFFCBC4)
private val md_theme_ember_dark_inversePrimary = Color(0xFFB91B1B)
private val md_theme_ember_dark_secondary = Color(0xFFFFB4AB)
private val md_theme_ember_dark_onSecondary = Color(0xFF61110E)
private val md_theme_ember_dark_secondaryContainer = Color(0xFF832A24)
private val md_theme_ember_dark_onSecondaryContainer = Color(0xFFFF9F94)
private val md_theme_ember_dark_tertiary = Color(0xFFA5C8FF)
private val md_theme_ember_dark_onTertiary = Color(0xFF00315E)
private val md_theme_ember_dark_tertiaryContainer = Color(0xFF005EAC)
private val md_theme_ember_dark_onTertiaryContainer = Color(0xFFC1D8FF)
private val md_theme_ember_dark_background = Color(0xFF000000)
private val md_theme_ember_dark_onBackground = Color(0xFFFADCD8)
private val md_theme_ember_dark_surface = Color(0xFF000000)
private val md_theme_ember_dark_onSurface = Color(0xFFFADCD8)
private val md_theme_ember_dark_surfaceVariant = Color(0xFF5B403D)
private val md_theme_ember_dark_onSurfaceVariant = Color(0xFFE4BEB9)
private val md_theme_ember_dark_surfaceTint = Color(0xFFFFB4AB)
private val md_theme_ember_dark_inverseSurface = Color(0xFFFADCD8)
private val md_theme_ember_dark_inverseOnSurface = Color(0xFF3E2C2A)
private val md_theme_ember_dark_error = Color(0xFFFFB4AB)
private val md_theme_ember_dark_onError = Color(0xFF690005)
private val md_theme_ember_dark_errorContainer = Color(0xFF93000A)
private val md_theme_ember_dark_onErrorContainer = Color(0xFFFFDAD6)
private val md_theme_ember_dark_outline = Color(0xFFAB8984)
private val md_theme_ember_dark_outlineVariant = Color(0xFF5B403D)
private val md_theme_ember_dark_scrim = Color(0xFF000000)
private val md_theme_ember_dark_surfaceBright = Color(0xFF473532)
private val md_theme_ember_dark_surfaceDim = Color(0xFF1E100E)
private val md_theme_ember_dark_surfaceContainer = Color(0xFF2C1C1A)
private val md_theme_ember_dark_surfaceContainerHigh = Color(0xFF372624)
private val md_theme_ember_dark_surfaceContainerHighest = Color(0xFF43302E)
private val md_theme_ember_dark_surfaceContainerLow = Color(0xFF271816)
private val md_theme_ember_dark_surfaceContainerLowest = Color(0xFF180A09)

// fern
private val md_theme_fern_light_primary = Color(0xFF144D19)
private val md_theme_fern_light_onPrimary = Color(0xFFFFFFFF)
private val md_theme_fern_light_primaryContainer = Color(0xFF2E662E)
private val md_theme_fern_light_onPrimaryContainer = Color(0xFFA4E29C)
private val md_theme_fern_light_inversePrimary = Color(0xFF98D691)
private val md_theme_fern_light_secondary = Color(0xFF4D6449)
private val md_theme_fern_light_onSecondary = Color(0xFFFFFFFF)
private val md_theme_fern_light_secondaryContainer = Color(0xFFCDE7C5)
private val md_theme_fern_light_onSecondaryContainer = Color(0xFF51694D)
private val md_theme_fern_light_tertiary = Color(0xFF712A45)
private val md_theme_fern_light_onTertiary = Color(0xFFFFFFFF)
private val md_theme_fern_light_tertiaryContainer = Color(0xFF8E415C)
private val md_theme_fern_light_onTertiaryContainer = Color(0xFFFFC2D3)
private val md_theme_fern_light_background = Color(0xFFF1F4EE)
private val md_theme_fern_light_onBackground = Color(0xFF191D18)
private val md_theme_fern_light_surface = Color(0xFFF1F4EE)
private val md_theme_fern_light_onSurface = Color(0xFF191D18)
private val md_theme_fern_light_surfaceVariant = Color(0xFFDDE5D7)
private val md_theme_fern_light_onSurfaceVariant = Color(0xFF41493E)
private val md_theme_fern_light_surfaceTint = Color(0xFF326A32)
private val md_theme_fern_light_inverseSurface = Color(0xFF2E312C)
private val md_theme_fern_light_inverseOnSurface = Color(0xFFEFF2E9)
private val md_theme_fern_light_error = Color(0xFFBA1A1A)
private val md_theme_fern_light_onError = Color(0xFFFFFFFF)
private val md_theme_fern_light_errorContainer = Color(0xFFFFDAD6)
private val md_theme_fern_light_onErrorContainer = Color(0xFF93000A)
private val md_theme_fern_light_outline = Color(0xFF71796D)
private val md_theme_fern_light_outlineVariant = Color(0xFFC1C9BB)
private val md_theme_fern_light_scrim = Color(0xFF000000)
private val md_theme_fern_light_surfaceBright = Color(0xFFF8FAF2)
private val md_theme_fern_light_surfaceDim = Color(0xFFD8DBD3)
private val md_theme_fern_light_surfaceContainer = Color(0xFFECEFE7)
private val md_theme_fern_light_surfaceContainerHigh = Color(0xFFE7E9E1)
private val md_theme_fern_light_surfaceContainerHighest = Color(0xFFE1E3DB)
private val md_theme_fern_light_surfaceContainerLow = Color(0xFFF2F5EC)
private val md_theme_fern_light_surfaceContainerLowest = Color(0xFFFFFFFF)
private val md_theme_fern_dark_primary = Color(0xFFA7E999)
private val md_theme_fern_dark_onPrimary = Color(0xFF003A04)
private val md_theme_fern_dark_primaryContainer = Color(0xFF8CCC80)
private val md_theme_fern_dark_onPrimaryContainer = Color(0xFF1B5719)
private val md_theme_fern_dark_inversePrimary = Color(0xFF306B2B)
private val md_theme_fern_dark_secondary = Color(0xFFB3CEA9)
private val md_theme_fern_dark_onSecondary = Color(0xFF1F361C)
private val md_theme_fern_dark_secondaryContainer = Color(0xFF354D30)
private val md_theme_fern_dark_onSecondaryContainer = Color(0xFFA2BD99)
private val md_theme_fern_dark_tertiary = Color(0xFFFFCADB)
private val md_theme_fern_dark_onTertiary = Color(0xFF591736)
private val md_theme_fern_dark_tertiaryContainer = Color(0xFFFFA0C3)
private val md_theme_fern_dark_onTertiaryContainer = Color(0xFF7B3251)
private val md_theme_fern_dark_background = Color(0xFF050A06)
private val md_theme_fern_dark_onBackground = Color(0xFFE1E4DB)
private val md_theme_fern_dark_surface = Color(0xFF050A06)
private val md_theme_fern_dark_onSurface = Color(0xFFE1E4DB)
private val md_theme_fern_dark_surfaceVariant = Color(0xFF41493E)
private val md_theme_fern_dark_onSurfaceVariant = Color(0xFFC1C9BA)
private val md_theme_fern_dark_surfaceTint = Color(0xFF96D789)
private val md_theme_fern_dark_inverseSurface = Color(0xFFE1E4DB)
private val md_theme_fern_dark_inverseOnSurface = Color(0xFF2E312C)
private val md_theme_fern_dark_error = Color(0xFFFFB4AB)
private val md_theme_fern_dark_onError = Color(0xFF690005)
private val md_theme_fern_dark_errorContainer = Color(0xFF93000A)
private val md_theme_fern_dark_onErrorContainer = Color(0xFFFFDAD6)
private val md_theme_fern_dark_outline = Color(0xFF8B9386)
private val md_theme_fern_dark_outlineVariant = Color(0xFF41493E)
private val md_theme_fern_dark_scrim = Color(0xFF000000)
private val md_theme_fern_dark_surfaceBright = Color(0xFF363A34)
private val md_theme_fern_dark_surfaceDim = Color(0xFF11140F)
private val md_theme_fern_dark_surfaceContainer = Color(0xFF1D211B)
private val md_theme_fern_dark_surfaceContainerHigh = Color(0xFF272B25)
private val md_theme_fern_dark_surfaceContainerHighest = Color(0xFF323630)
private val md_theme_fern_dark_surfaceContainerLow = Color(0xFF191D17)
private val md_theme_fern_dark_surfaceContainerLowest = Color(0xFF0C0F0A)

// marine
private val md_theme_marine_light_primary = Color(0xFF00296D)
private val md_theme_marine_light_onPrimary = Color(0xFFFFFFFF)
private val md_theme_marine_light_primaryContainer = Color(0xFF1A408C)
private val md_theme_marine_light_onPrimaryContainer = Color(0xFF92AFFF)
private val md_theme_marine_light_inversePrimary = Color(0xFFB1C5FF)
private val md_theme_marine_light_secondary = Color(0xFF535E7D)
private val md_theme_marine_light_onSecondary = Color(0xFFFFFFFF)
private val md_theme_marine_light_secondaryContainer = Color(0xFFCED9FE)
private val md_theme_marine_light_onSecondaryContainer = Color(0xFF535E7E)
private val md_theme_marine_light_tertiary = Color(0xFF501F00)
private val md_theme_marine_light_onTertiary = Color(0xFFFFFFFF)
private val md_theme_marine_light_tertiaryContainer = Color(0xFF733000)
private val md_theme_marine_light_onTertiaryContainer = Color(0xFFFA9963)
private val md_theme_marine_light_background = Color(0xFFF0F4F8)
private val md_theme_marine_light_onBackground = Color(0xFF1A1B20)
private val md_theme_marine_light_surface = Color(0xFFF0F4F8)
private val md_theme_marine_light_onSurface = Color(0xFF1A1B20)
private val md_theme_marine_light_surfaceVariant = Color(0xFFE0E2EF)
private val md_theme_marine_light_onSurfaceVariant = Color(0xFF444651)
private val md_theme_marine_light_surfaceTint = Color(0xFF3A5BA8)
private val md_theme_marine_light_inverseSurface = Color(0xFF2F3036)
private val md_theme_marine_light_inverseOnSurface = Color(0xFFF1F0F7)
private val md_theme_marine_light_error = Color(0xFFBA1A1A)
private val md_theme_marine_light_onError = Color(0xFFFFFFFF)
private val md_theme_marine_light_errorContainer = Color(0xFFFFDAD6)
private val md_theme_marine_light_onErrorContainer = Color(0xFF93000A)
private val md_theme_marine_light_outline = Color(0xFF747782)
private val md_theme_marine_light_outlineVariant = Color(0xFFC4C6D3)
private val md_theme_marine_light_scrim = Color(0xFF000000)
private val md_theme_marine_light_surfaceBright = Color(0xFFFAF8FF)
private val md_theme_marine_light_surfaceDim = Color(0xFFDAD9E0)
private val md_theme_marine_light_surfaceContainer = Color(0xFFEEEDF4)
private val md_theme_marine_light_surfaceContainerHigh = Color(0xFFE8E7EF)
private val md_theme_marine_light_surfaceContainerHighest = Color(0xFFE2E2E9)
private val md_theme_marine_light_surfaceContainerLow = Color(0xFFF4F3FA)
private val md_theme_marine_light_surfaceContainerLowest = Color(0xFFFFFFFF)
private val md_theme_marine_dark_primary = Color(0xFFB3C5FF)
private val md_theme_marine_dark_onPrimary = Color(0xFF002A76)
private val md_theme_marine_dark_primaryContainer = Color(0xFF385EBD)
private val md_theme_marine_dark_onPrimaryContainer = Color(0xFFD8DFFF)
private val md_theme_marine_dark_inversePrimary = Color(0xFF3259B8)
private val md_theme_marine_dark_secondary = Color(0xFFB9C5F1)
private val md_theme_marine_dark_onSecondary = Color(0xFF222F52)
private val md_theme_marine_dark_secondaryContainer = Color(0xFF3C486C)
private val md_theme_marine_dark_onSecondaryContainer = Color(0xFFABB7E2)
private val md_theme_marine_dark_tertiary = Color(0xFFFFB784)
private val md_theme_marine_dark_onTertiary = Color(0xFF502500)
private val md_theme_marine_dark_tertiaryContainer = Color(0xFF9C4E00)
private val md_theme_marine_dark_onTertiaryContainer = Color(0xFFFFD9C1)
private val md_theme_marine_dark_background = Color(0xFF040C16)
private val md_theme_marine_dark_onBackground = Color(0xFFE2E2EA)
private val md_theme_marine_dark_surface = Color(0xFF040C16)
private val md_theme_marine_dark_onSurface = Color(0xFFE2E2EA)
private val md_theme_marine_dark_surfaceVariant = Color(0xFF434652)
private val md_theme_marine_dark_onSurfaceVariant = Color(0xFFC4C6D4)
private val md_theme_marine_dark_surfaceTint = Color(0xFFB3C5FF)
private val md_theme_marine_dark_inverseSurface = Color(0xFFE2E2EA)
private val md_theme_marine_dark_inverseOnSurface = Color(0xFF2F3037)
private val md_theme_marine_dark_error = Color(0xFFFFB4AB)
private val md_theme_marine_dark_onError = Color(0xFF690005)
private val md_theme_marine_dark_errorContainer = Color(0xFF93000A)
private val md_theme_marine_dark_onErrorContainer = Color(0xFFFFDAD6)
private val md_theme_marine_dark_outline = Color(0xFF8E909E)
private val md_theme_marine_dark_outlineVariant = Color(0xFF434652)
private val md_theme_marine_dark_scrim = Color(0xFF000000)
private val md_theme_marine_dark_surfaceBright = Color(0xFF383940)
private val md_theme_marine_dark_surfaceDim = Color(0xFF121319)
private val md_theme_marine_dark_surfaceContainer = Color(0xFF1E1F26)
private val md_theme_marine_dark_surfaceContainerHigh = Color(0xFF282A30)
private val md_theme_marine_dark_surfaceContainerHighest = Color(0xFF33343B)
private val md_theme_marine_dark_surfaceContainerLow = Color(0xFF1A1B21)
private val md_theme_marine_dark_surfaceContainerLowest = Color(0xFF0C0E14)

// olive
private val md_theme_olive_light_primary = Color(0xFF354E18)
private val md_theme_olive_light_onPrimary = Color(0xFFFFFFFF)
private val md_theme_olive_light_primaryContainer = Color(0xFF4C662E)
private val md_theme_olive_light_onPrimaryContainer = Color(0xFFC4E39D)
private val md_theme_olive_light_inversePrimary = Color(0xFFB2D08D)
private val md_theme_olive_light_secondary = Color(0xFF576248)
private val md_theme_olive_light_onSecondary = Color(0xFFFFFFFF)
private val md_theme_olive_light_secondaryContainer = Color(0xFFD8E4C3)
private val md_theme_olive_light_onSecondaryContainer = Color(0xFF5B664C)
private val md_theme_olive_light_tertiary = Color(0xFF66365B)
private val md_theme_olive_light_onTertiary = Color(0xFFFFFFFF)
private val md_theme_olive_light_tertiaryContainer = Color(0xFF814D74)
private val md_theme_olive_light_onTertiaryContainer = Color(0xFFFFC8ED)
private val md_theme_olive_light_background = Color(0xFFF4F3EC)
private val md_theme_olive_light_onBackground = Color(0xFF1B1C17)
private val md_theme_olive_light_surface = Color(0xFFF4F3EC)
private val md_theme_olive_light_onSurface = Color(0xFF1B1C17)
private val md_theme_olive_light_surfaceVariant = Color(0xFFE1E4D5)
private val md_theme_olive_light_onSurfaceVariant = Color(0xFF44483D)
private val md_theme_olive_light_surfaceTint = Color(0xFF4C662E)
private val md_theme_olive_light_inverseSurface = Color(0xFF2F312C)
private val md_theme_olive_light_inverseOnSurface = Color(0xFFF1F1E9)
private val md_theme_olive_light_error = Color(0xFFBA1A1A)
private val md_theme_olive_light_onError = Color(0xFFFFFFFF)
private val md_theme_olive_light_errorContainer = Color(0xFFFFDAD6)
private val md_theme_olive_light_onErrorContainer = Color(0xFF93000A)
private val md_theme_olive_light_outline = Color(0xFF74796C)
private val md_theme_olive_light_outlineVariant = Color(0xFFC4C8B9)
private val md_theme_olive_light_scrim = Color(0xFF000000)
private val md_theme_olive_light_surfaceBright = Color(0xFFFAFAF1)
private val md_theme_olive_light_surfaceDim = Color(0xFFDBDAD3)
private val md_theme_olive_light_surfaceContainer = Color(0xFFEFEEE6)
private val md_theme_olive_light_surfaceContainerHigh = Color(0xFFE9E9E1)
private val md_theme_olive_light_surfaceContainerHighest = Color(0xFFE3E3DB)
private val md_theme_olive_light_surfaceContainerLow = Color(0xFFF4F4EC)
private val md_theme_olive_light_surfaceContainerLowest = Color(0xFFFFFFFF)
private val md_theme_olive_dark_primary = Color(0xFFB5D171)
private val md_theme_olive_dark_onPrimary = Color(0xFF273500)
private val md_theme_olive_dark_primaryContainer = Color(0xFF8CA64C)
private val md_theme_olive_dark_onPrimaryContainer = Color(0xFF2A3900)
private val md_theme_olive_dark_inversePrimary = Color(0xFF4F6612)
private val md_theme_olive_dark_secondary = Color(0xFFC0CC9E)
private val md_theme_olive_dark_onSecondary = Color(0xFF2A3413)
private val md_theme_olive_dark_secondaryContainer = Color(0xFF414B28)
private val md_theme_olive_dark_onSecondaryContainer = Color(0xFFAEBA8E)
private val md_theme_olive_dark_tertiary = Color(0xFFF6AFF5)
private val md_theme_olive_dark_onTertiary = Color(0xFF501854)
private val md_theme_olive_dark_tertiaryContainer = Color(0xFFC885C8)
private val md_theme_olive_dark_onTertiaryContainer = Color(0xFF531C58)
private val md_theme_olive_dark_background = Color(0xFF090902)
private val md_theme_olive_dark_onBackground = Color(0xFFE3E3D8)
private val md_theme_olive_dark_surface = Color(0xFF090902)
private val md_theme_olive_dark_onSurface = Color(0xFFE3E3D8)
private val md_theme_olive_dark_surfaceVariant = Color(0xFF45483A)
private val md_theme_olive_dark_onSurfaceVariant = Color(0xFFC5C8B6)
private val md_theme_olive_dark_surfaceTint = Color(0xFFB5D171)
private val md_theme_olive_dark_inverseSurface = Color(0xFFE3E3D8)
private val md_theme_olive_dark_inverseOnSurface = Color(0xFF30312A)
private val md_theme_olive_dark_error = Color(0xFFFFB4AB)
private val md_theme_olive_dark_onError = Color(0xFF690005)
private val md_theme_olive_dark_errorContainer = Color(0xFF93000A)
private val md_theme_olive_dark_onErrorContainer = Color(0xFFFFDAD6)
private val md_theme_olive_dark_outline = Color(0xFF8F9281)
private val md_theme_olive_dark_outlineVariant = Color(0xFF45483A)
private val md_theme_olive_dark_scrim = Color(0xFF000000)
private val md_theme_olive_dark_surfaceBright = Color(0xFF383A32)
private val md_theme_olive_dark_surfaceDim = Color(0xFF12140E)
private val md_theme_olive_dark_surfaceContainer = Color(0xFF1F201A)
private val md_theme_olive_dark_surfaceContainerHigh = Color(0xFF292B24)
private val md_theme_olive_dark_surfaceContainerHighest = Color(0xFF34352E)
private val md_theme_olive_dark_surfaceContainerLow = Color(0xFF1B1C16)
private val md_theme_olive_dark_surfaceContainerLowest = Color(0xFF0D0F09)

// lavender
private val md_theme_lavender_light_primary = Color(0xFF532D93)
private val md_theme_lavender_light_onPrimary = Color(0xFFFFFFFF)
private val md_theme_lavender_light_primaryContainer = Color(0xFF6B47AD)
private val md_theme_lavender_light_onPrimaryContainer = Color(0xFFDFCCFF)
private val md_theme_lavender_light_inversePrimary = Color(0xFFD3BBFF)
private val md_theme_lavender_light_secondary = Color(0xFF665780)
private val md_theme_lavender_light_onSecondary = Color(0xFFFFFFFF)
private val md_theme_lavender_light_secondaryContainer = Color(0xFFE1CFFF)
private val md_theme_lavender_light_onSecondaryContainer = Color(0xFF65567F)
private val md_theme_lavender_light_tertiary = Color(0xFF5C3F00)
private val md_theme_lavender_light_onTertiary = Color(0xFFFFFFFF)
private val md_theme_lavender_light_tertiaryContainer = Color(0xFF7A5500)
private val md_theme_lavender_light_onTertiaryContainer = Color(0xFFFFCD77)
private val md_theme_lavender_light_background = Color(0xFFF4F1F8)
private val md_theme_lavender_light_onBackground = Color(0xFF1D1A21)
private val md_theme_lavender_light_surface = Color(0xFFF4F1F8)
private val md_theme_lavender_light_onSurface = Color(0xFF1D1A21)
private val md_theme_lavender_light_surfaceVariant = Color(0xFFE8DFF0)
private val md_theme_lavender_light_onSurfaceVariant = Color(0xFF4A4451)
private val md_theme_lavender_light_surfaceTint = Color(0xFF6E4AB0)
private val md_theme_lavender_light_inverseSurface = Color(0xFF322F36)
private val md_theme_lavender_light_inverseOnSurface = Color(0xFFF6EEF8)
private val md_theme_lavender_light_error = Color(0xFFBA1A1A)
private val md_theme_lavender_light_onError = Color(0xFFFFFFFF)
private val md_theme_lavender_light_errorContainer = Color(0xFFFFDAD6)
private val md_theme_lavender_light_onErrorContainer = Color(0xFF93000A)
private val md_theme_lavender_light_outline = Color(0xFF7B7483)
private val md_theme_lavender_light_outlineVariant = Color(0xFFCCC3D3)
private val md_theme_lavender_light_scrim = Color(0xFF000000)
private val md_theme_lavender_light_surfaceBright = Color(0xFFFEF7FF)
private val md_theme_lavender_light_surfaceDim = Color(0xFFDED8E1)
private val md_theme_lavender_light_surfaceContainer = Color(0xFFF3EBF5)
private val md_theme_lavender_light_surfaceContainerHigh = Color(0xFFEDE6EF)
private val md_theme_lavender_light_surfaceContainerHighest = Color(0xFFE7E0EA)
private val md_theme_lavender_light_surfaceContainerLow = Color(0xFFF8F1FB)
private val md_theme_lavender_light_surfaceContainerLowest = Color(0xFFFFFFFF)
private val md_theme_lavender_dark_primary = Color(0xFFDFC5FF)
private val md_theme_lavender_dark_onPrimary = Color(0xFF3E2163)
private val md_theme_lavender_dark_primaryContainer = Color(0xFFC7A6F2)
private val md_theme_lavender_dark_onPrimaryContainer = Color(0xFF54387B)
private val md_theme_lavender_dark_inversePrimary = Color(0xFF6E5095)
private val md_theme_lavender_dark_secondary = Color(0xFFD1C0E2)
private val md_theme_lavender_dark_onSecondary = Color(0xFF372B46)
private val md_theme_lavender_dark_secondaryContainer = Color(0xFF4E415D)
private val md_theme_lavender_dark_onSecondaryContainer = Color(0xFFBFAFD0)
private val md_theme_lavender_dark_tertiary = Color(0xFFD8D46E)
private val md_theme_lavender_dark_onTertiary = Color(0xFF343200)
private val md_theme_lavender_dark_tertiaryContainer = Color(0xFFBCB856)
private val md_theme_lavender_dark_onTertiaryContainer = Color(0xFF4A4800)
private val md_theme_lavender_dark_background = Color(0xFF0B0512)
private val md_theme_lavender_dark_onBackground = Color(0xFFE7E0E7)
private val md_theme_lavender_dark_surface = Color(0xFF0B0512)
private val md_theme_lavender_dark_onSurface = Color(0xFFE7E0E7)
private val md_theme_lavender_dark_surfaceVariant = Color(0xFF4A454F)
private val md_theme_lavender_dark_onSurfaceVariant = Color(0xFFCCC3D0)
private val md_theme_lavender_dark_surfaceTint = Color(0xFFD8B9FF)
private val md_theme_lavender_dark_inverseSurface = Color(0xFFE7E0E7)
private val md_theme_lavender_dark_inverseOnSurface = Color(0xFF322F34)
private val md_theme_lavender_dark_error = Color(0xFFFFB4AB)
private val md_theme_lavender_dark_onError = Color(0xFF690005)
private val md_theme_lavender_dark_errorContainer = Color(0xFF93000A)
private val md_theme_lavender_dark_onErrorContainer = Color(0xFFFFDAD6)
private val md_theme_lavender_dark_outline = Color(0xFF958E9A)
private val md_theme_lavender_dark_outlineVariant = Color(0xFF4A454F)
private val md_theme_lavender_dark_scrim = Color(0xFF000000)
private val md_theme_lavender_dark_surfaceBright = Color(0xFF3B383D)
private val md_theme_lavender_dark_surfaceDim = Color(0xFF151217)
private val md_theme_lavender_dark_surfaceContainer = Color(0xFF211F23)
private val md_theme_lavender_dark_surfaceContainerHigh = Color(0xFF2C292E)
private val md_theme_lavender_dark_surfaceContainerHighest = Color(0xFF373439)
private val md_theme_lavender_dark_surfaceContainerLow = Color(0xFF1D1B1F)
private val md_theme_lavender_dark_surfaceContainerLowest = Color(0xFF0F0D12)

// sakura
private val md_theme_sakura_light_primary = Color(0xFF6F195A)
private val md_theme_sakura_light_onPrimary = Color(0xFFFFFFFF)
private val md_theme_sakura_light_primaryContainer = Color(0xFF8C3373)
private val md_theme_sakura_light_onPrimaryContainer = Color(0xFFFFB4E2)
private val md_theme_sakura_light_inversePrimary = Color(0xFFFFADE0)
private val md_theme_sakura_light_secondary = Color(0xFF7C516C)
private val md_theme_sakura_light_onSecondary = Color(0xFFFFFFFF)
private val md_theme_sakura_light_secondaryContainer = Color(0xFFFEC7E7)
private val md_theme_sakura_light_onSecondaryContainer = Color(0xFF7B506B)
private val md_theme_sakura_light_tertiary = Color(0xFF244700)
private val md_theme_sakura_light_onTertiary = Color(0xFFFFFFFF)
private val md_theme_sakura_light_tertiaryContainer = Color(0xFF336100)
private val md_theme_sakura_light_onTertiaryContainer = Color(0xFFA4DB72)
private val md_theme_sakura_light_background = Color(0xFFF8F2F4)
private val md_theme_sakura_light_onBackground = Color(0xFF21191E)
private val md_theme_sakura_light_surface = Color(0xFFF8F2F4)
private val md_theme_sakura_light_onSurface = Color(0xFF21191E)
private val md_theme_sakura_light_surfaceVariant = Color(0xFFF3DCE7)
private val md_theme_sakura_light_onSurfaceVariant = Color(0xFF52424B)
private val md_theme_sakura_light_surfaceTint = Color(0xFF973C7C)
private val md_theme_sakura_light_inverseSurface = Color(0xFF372E33)
private val md_theme_sakura_light_inverseOnSurface = Color(0xFFFCEDF3)
private val md_theme_sakura_light_error = Color(0xFFBA1A1A)
private val md_theme_sakura_light_onError = Color(0xFFFFFFFF)
private val md_theme_sakura_light_errorContainer = Color(0xFFFFDAD6)
private val md_theme_sakura_light_onErrorContainer = Color(0xFF93000A)
private val md_theme_sakura_light_outline = Color(0xFF84727B)
private val md_theme_sakura_light_outlineVariant = Color(0xFFD7C1CB)
private val md_theme_sakura_light_scrim = Color(0xFF000000)
private val md_theme_sakura_light_surfaceBright = Color(0xFFFFF8F9)
private val md_theme_sakura_light_surfaceDim = Color(0xFFE5D6DC)
private val md_theme_sakura_light_surfaceContainer = Color(0xFFFAEAF0)
private val md_theme_sakura_light_surfaceContainerHigh = Color(0xFFF4E4EA)
private val md_theme_sakura_light_surfaceContainerHighest = Color(0xFFEEDFE5)
private val md_theme_sakura_light_surfaceContainerLow = Color(0xFFFFF0F5)
private val md_theme_sakura_light_surfaceContainerLowest = Color(0xFFFFFFFF)
private val md_theme_sakura_dark_primary = Color(0xFFFFD5E7)
private val md_theme_sakura_dark_onPrimary = Color(0xFF4D213A)
private val md_theme_sakura_dark_primaryContainer = Color(0xFFF2B2D1)
private val md_theme_sakura_dark_onPrimaryContainer = Color(0xFF73415C)
private val md_theme_sakura_dark_inversePrimary = Color(0xFF824E69)
private val md_theme_sakura_dark_secondary = Color(0xFFDEBECC)
private val md_theme_sakura_dark_onSecondary = Color(0xFF402A35)
private val md_theme_sakura_dark_secondaryContainer = Color(0xFF58404B)
private val md_theme_sakura_dark_onSecondaryContainer = Color(0xFFCCADBA)
private val md_theme_sakura_dark_tertiary = Color(0xFFC7EAB2)
private val md_theme_sakura_dark_onTertiary = Color(0xFF1C3710)
private val md_theme_sakura_dark_tertiaryContainer = Color(0xFFACCE98)
private val md_theme_sakura_dark_onTertiaryContainer = Color(0xFF3B582E)
private val md_theme_sakura_dark_background = Color(0xFF10060A)
private val md_theme_sakura_dark_onBackground = Color(0xFFEAE0E2)
private val md_theme_sakura_dark_surface = Color(0xFF10060A)
private val md_theme_sakura_dark_onSurface = Color(0xFFEAE0E2)
private val md_theme_sakura_dark_surfaceVariant = Color(0xFF504349)
private val md_theme_sakura_dark_onSurfaceVariant = Color(0xFFD3C2C8)
private val md_theme_sakura_dark_surfaceTint = Color(0xFFF4B4D3)
private val md_theme_sakura_dark_inverseSurface = Color(0xFFEAE0E2)
private val md_theme_sakura_dark_inverseOnSurface = Color(0xFF352F31)
private val md_theme_sakura_dark_error = Color(0xFFFFB4AB)
private val md_theme_sakura_dark_onError = Color(0xFF690005)
private val md_theme_sakura_dark_errorContainer = Color(0xFF93000A)
private val md_theme_sakura_dark_onErrorContainer = Color(0xFFFFDAD6)
private val md_theme_sakura_dark_outline = Color(0xFF9C8D92)
private val md_theme_sakura_dark_outlineVariant = Color(0xFF504349)
private val md_theme_sakura_dark_scrim = Color(0xFF000000)
private val md_theme_sakura_dark_surfaceBright = Color(0xFF3E383A)
private val md_theme_sakura_dark_surfaceDim = Color(0xFF171214)
private val md_theme_sakura_dark_surfaceContainer = Color(0xFF231E20)
private val md_theme_sakura_dark_surfaceContainerHigh = Color(0xFF2E292B)
private val md_theme_sakura_dark_surfaceContainerHighest = Color(0xFF393335)
private val md_theme_sakura_dark_surfaceContainerLow = Color(0xFF1F1A1C)
private val md_theme_sakura_dark_surfaceContainerLowest = Color(0xFF110D0F)

// solarized
private val md_theme_solarized_light_primary = Color(0xFF005E94)
private val md_theme_solarized_light_onPrimary = Color(0xFFFFFFFF)
private val md_theme_solarized_light_primaryContainer = Color(0xFF1E77B5)
private val md_theme_solarized_light_onPrimaryContainer = Color(0xFFF6F8FF)
private val md_theme_solarized_light_inversePrimary = Color(0xFF97CBFF)
private val md_theme_solarized_light_secondary = Color(0xFF47617A)
private val md_theme_solarized_light_onSecondary = Color(0xFFFFFFFF)
private val md_theme_solarized_light_secondaryContainer = Color(0xFFC5E0FD)
private val md_theme_solarized_light_onSecondaryContainer = Color(0xFF4A637C)
private val md_theme_solarized_light_tertiary = Color(0xFF824D00)
private val md_theme_solarized_light_onTertiary = Color(0xFFFFFFFF)
private val md_theme_solarized_light_tertiaryContainer = Color(0xFFA46300)
private val md_theme_solarized_light_onTertiaryContainer = Color(0xFFFFF7F2)
private val md_theme_solarized_light_background = Color(0xFFEEE8D5)
private val md_theme_solarized_light_onBackground = Color(0xFF181C20)
private val md_theme_solarized_light_surface = Color(0xFFEEE8D5)
private val md_theme_solarized_light_onSurface = Color(0xFF181C20)
private val md_theme_solarized_light_surfaceVariant = Color(0xFFDCE3EE)
private val md_theme_solarized_light_onSurfaceVariant = Color(0xFF404750)
private val md_theme_solarized_light_surfaceTint = Color(0xFF00639B)
private val md_theme_solarized_light_inverseSurface = Color(0xFF2D3135)
private val md_theme_solarized_light_inverseOnSurface = Color(0xFFEFF1F6)
private val md_theme_solarized_light_error = Color(0xFFBA1A1A)
private val md_theme_solarized_light_onError = Color(0xFFFFFFFF)
private val md_theme_solarized_light_errorContainer = Color(0xFFFFDAD6)
private val md_theme_solarized_light_onErrorContainer = Color(0xFF93000A)
private val md_theme_solarized_light_outline = Color(0xFF707881)
private val md_theme_solarized_light_outlineVariant = Color(0xFFC0C7D1)
private val md_theme_solarized_light_scrim = Color(0xFF000000)
private val md_theme_solarized_light_surfaceBright = Color(0xFFF7F9FF)
private val md_theme_solarized_light_surfaceDim = Color(0xFFD8DADF)
private val md_theme_solarized_light_surfaceContainer = Color(0xFFECEEF3)
private val md_theme_solarized_light_surfaceContainerHigh = Color(0xFFE6E8EE)
private val md_theme_solarized_light_surfaceContainerHighest = Color(0xFFE0E2E8)
private val md_theme_solarized_light_surfaceContainerLow = Color(0xFFF2F3F9)
private val md_theme_solarized_light_surfaceContainerLowest = Color(0xFFFFFFFF)
private val md_theme_solarized_dark_primary = Color(0xFF97CBFF)
private val md_theme_solarized_dark_onPrimary = Color(0xFF003353)
private val md_theme_solarized_dark_primaryContainer = Color(0xFF1E77B5)
private val md_theme_solarized_dark_onPrimaryContainer = Color(0xFFF6F8FF)
private val md_theme_solarized_dark_inversePrimary = Color(0xFF00639B)
private val md_theme_solarized_dark_secondary = Color(0xFFAFC9E6)
private val md_theme_solarized_dark_onSecondary = Color(0xFF183249)
private val md_theme_solarized_dark_secondaryContainer = Color(0xFF2F4961)
private val md_theme_solarized_dark_onSecondaryContainer = Color(0xFF9EB8D4)
private val md_theme_solarized_dark_tertiary = Color(0xFFFFB86A)
private val md_theme_solarized_dark_onTertiary = Color(0xFF492900)
private val md_theme_solarized_dark_tertiaryContainer = Color(0xFFA46300)
private val md_theme_solarized_dark_onTertiaryContainer = Color(0xFFFFF7F2)
private val md_theme_solarized_dark_background = Color(0xFF001E26)
private val md_theme_solarized_dark_onBackground = Color(0xFFE0E2E8)
private val md_theme_solarized_dark_surface = Color(0xFF001E26)
private val md_theme_solarized_dark_onSurface = Color(0xFFE0E2E8)
private val md_theme_solarized_dark_surfaceVariant = Color(0xFF404750)
private val md_theme_solarized_dark_onSurfaceVariant = Color(0xFFC0C7D1)
private val md_theme_solarized_dark_surfaceTint = Color(0xFF97CBFF)
private val md_theme_solarized_dark_inverseSurface = Color(0xFFE0E2E8)
private val md_theme_solarized_dark_inverseOnSurface = Color(0xFF2D3135)
private val md_theme_solarized_dark_error = Color(0xFFFFB4AB)
private val md_theme_solarized_dark_onError = Color(0xFF690005)
private val md_theme_solarized_dark_errorContainer = Color(0xFF93000A)
private val md_theme_solarized_dark_onErrorContainer = Color(0xFFFFDAD6)
private val md_theme_solarized_dark_outline = Color(0xFF8A919B)
private val md_theme_solarized_dark_outlineVariant = Color(0xFF404750)
private val md_theme_solarized_dark_scrim = Color(0xFF000000)
private val md_theme_solarized_dark_surfaceBright = Color(0xFF36393E)
private val md_theme_solarized_dark_surfaceDim = Color(0xFF101418)
private val md_theme_solarized_dark_surfaceContainer = Color(0xFF1C2024)
private val md_theme_solarized_dark_surfaceContainerHigh = Color(0xFF272A2F)
private val md_theme_solarized_dark_surfaceContainerHighest = Color(0xFF323539)
private val md_theme_solarized_dark_surfaceContainerLow = Color(0xFF181C20)
private val md_theme_solarized_dark_surfaceContainerLowest = Color(0xFF0B0E12)

// nord
private val md_theme_nord_light_primary = Color(0xFF325684)
private val md_theme_nord_light_onPrimary = Color(0xFFFFFFFF)
private val md_theme_nord_light_primaryContainer = Color(0xFF4C6F9E)
private val md_theme_nord_light_onPrimaryContainer = Color(0xFFEBF1FF)
private val md_theme_nord_light_inversePrimary = Color(0xFFA6C9FD)
private val md_theme_nord_light_secondary = Color(0xFF535F73)
private val md_theme_nord_light_onSecondary = Color(0xFFFFFFFF)
private val md_theme_nord_light_secondaryContainer = Color(0xFFD6E3FB)
private val md_theme_nord_light_onSecondaryContainer = Color(0xFF596579)
private val md_theme_nord_light_tertiary = Color(0xFF705004)
private val md_theme_nord_light_onTertiary = Color(0xFFFFFFFF)
private val md_theme_nord_light_tertiaryContainer = Color(0xFF8B681F)
private val md_theme_nord_light_onTertiaryContainer = Color(0xFFFFEFD9)
private val md_theme_nord_light_background = Color(0xFFECEFF4)
private val md_theme_nord_light_onBackground = Color(0xFF1A1C1F)
private val md_theme_nord_light_surface = Color(0xFFECEFF4)
private val md_theme_nord_light_onSurface = Color(0xFF1A1C1F)
private val md_theme_nord_light_surfaceVariant = Color(0xFFDFE2EC)
private val md_theme_nord_light_onSurfaceVariant = Color(0xFF43474F)
private val md_theme_nord_light_surfaceTint = Color(0xFF3C608E)
private val md_theme_nord_light_inverseSurface = Color(0xFF2F3034)
private val md_theme_nord_light_inverseOnSurface = Color(0xFFF1F0F5)
private val md_theme_nord_light_error = Color(0xFFBA1A1A)
private val md_theme_nord_light_onError = Color(0xFFFFFFFF)
private val md_theme_nord_light_errorContainer = Color(0xFFFFDAD6)
private val md_theme_nord_light_onErrorContainer = Color(0xFF93000A)
private val md_theme_nord_light_outline = Color(0xFF737780)
private val md_theme_nord_light_outlineVariant = Color(0xFFC3C6D0)
private val md_theme_nord_light_scrim = Color(0xFF000000)
private val md_theme_nord_light_surfaceBright = Color(0xFFFAF9FD)
private val md_theme_nord_light_surfaceDim = Color(0xFFDAD9DE)
private val md_theme_nord_light_surfaceContainer = Color(0xFFEEEDF2)
private val md_theme_nord_light_surfaceContainerHigh = Color(0xFFE8E8EC)
private val md_theme_nord_light_surfaceContainerHighest = Color(0xFFE2E2E6)
private val md_theme_nord_light_surfaceContainerLow = Color(0xFFF4F3F7)
private val md_theme_nord_light_surfaceContainerLowest = Color(0xFFFFFFFF)
private val md_theme_nord_dark_primary = Color(0xFFBCECFB)
private val md_theme_nord_dark_onPrimary = Color(0xFF003640)
private val md_theme_nord_dark_primaryContainer = Color(0xFFA0D0DE)
private val md_theme_nord_dark_onPrimaryContainer = Color(0xFF2A5A66)
private val md_theme_nord_dark_inversePrimary = Color(0xFF356571)
private val md_theme_nord_dark_secondary = Color(0xFFB7CAD0)
private val md_theme_nord_dark_onSecondary = Color(0xFF223338)
private val md_theme_nord_dark_secondaryContainer = Color(0xFF3B4C51)
private val md_theme_nord_dark_onSecondaryContainer = Color(0xFFA9BBC1)
private val md_theme_nord_dark_tertiary = Color(0xFFFFDEC9)
private val md_theme_nord_dark_onTertiary = Color(0xFF4B280B)
private val md_theme_nord_dark_tertiaryContainer = Color(0xFFF6BC95)
private val md_theme_nord_dark_onTertiaryContainer = Color(0xFF744A2B)
private val md_theme_nord_dark_background = Color(0xFF262B35)
private val md_theme_nord_dark_onBackground = Color(0xFFE2E2E3)
private val md_theme_nord_dark_surface = Color(0xFF262B35)
private val md_theme_nord_dark_onSurface = Color(0xFFE2E2E3)
private val md_theme_nord_dark_surfaceVariant = Color(0xFF40484A)
private val md_theme_nord_dark_onSurfaceVariant = Color(0xFFC0C8CA)
private val md_theme_nord_dark_surfaceTint = Color(0xFF9ECEDC)
private val md_theme_nord_dark_inverseSurface = Color(0xFFE2E2E3)
private val md_theme_nord_dark_inverseOnSurface = Color(0xFF2E3132)
private val md_theme_nord_dark_error = Color(0xFFFFB4AB)
private val md_theme_nord_dark_onError = Color(0xFF690005)
private val md_theme_nord_dark_errorContainer = Color(0xFF93000A)
private val md_theme_nord_dark_onErrorContainer = Color(0xFFFFDAD6)
private val md_theme_nord_dark_outline = Color(0xFF8A9295)
private val md_theme_nord_dark_outlineVariant = Color(0xFF40484A)
private val md_theme_nord_dark_scrim = Color(0xFF000000)
private val md_theme_nord_dark_surfaceBright = Color(0xFF37393A)
private val md_theme_nord_dark_surfaceDim = Color(0xFF111415)
private val md_theme_nord_dark_surfaceContainer = Color(0xFF1E2021)
private val md_theme_nord_dark_surfaceContainerHigh = Color(0xFF282A2B)
private val md_theme_nord_dark_surfaceContainerHighest = Color(0xFF333536)
private val md_theme_nord_dark_surfaceContainerLow = Color(0xFF1A1C1D)
private val md_theme_nord_dark_surfaceContainerLowest = Color(0xFF0C0F0F)

// catppuccin
private val md_theme_catppuccin_light_primary = Color(0xFF6E0AD6)
private val md_theme_catppuccin_light_onPrimary = Color(0xFFFFFFFF)
private val md_theme_catppuccin_light_primaryContainer = Color(0xFF8839EF)
private val md_theme_catppuccin_light_onPrimaryContainer = Color(0xFFF3E6FF)
private val md_theme_catppuccin_light_inversePrimary = Color(0xFFD7BAFF)
private val md_theme_catppuccin_light_secondary = Color(0xFF6F4DA1)
private val md_theme_catppuccin_light_onSecondary = Color(0xFFFFFFFF)
private val md_theme_catppuccin_light_secondaryContainer = Color(0xFFC7A2FD)
private val md_theme_catppuccin_light_onSecondaryContainer = Color(0xFF553386)
private val md_theme_catppuccin_light_tertiary = Color(0xFF7E4300)
private val md_theme_catppuccin_light_onTertiary = Color(0xFFFFFFFF)
private val md_theme_catppuccin_light_tertiaryContainer = Color(0xFFA15700)
private val md_theme_catppuccin_light_onTertiaryContainer = Color(0xFFFFE7D6)
private val md_theme_catppuccin_light_background = Color(0xFFEFF1F5)
private val md_theme_catppuccin_light_onBackground = Color(0xFF1E1A24)
private val md_theme_catppuccin_light_surface = Color(0xFFEFF1F5)
private val md_theme_catppuccin_light_onSurface = Color(0xFF1E1A24)
private val md_theme_catppuccin_light_surfaceVariant = Color(0xFFEADEF4)
private val md_theme_catppuccin_light_onSurfaceVariant = Color(0xFF4B4455)
private val md_theme_catppuccin_light_surfaceTint = Color(0xFF7C27E2)
private val md_theme_catppuccin_light_inverseSurface = Color(0xFF332E39)
private val md_theme_catppuccin_light_inverseOnSurface = Color(0xFFF7EDFC)
private val md_theme_catppuccin_light_error = Color(0xFFBA1A1A)
private val md_theme_catppuccin_light_onError = Color(0xFFFFFFFF)
private val md_theme_catppuccin_light_errorContainer = Color(0xFFFFDAD6)
private val md_theme_catppuccin_light_onErrorContainer = Color(0xFF93000A)
private val md_theme_catppuccin_light_outline = Color(0xFF7D7386)
private val md_theme_catppuccin_light_outlineVariant = Color(0xFFCEC2D8)
private val md_theme_catppuccin_light_scrim = Color(0xFF000000)
private val md_theme_catppuccin_light_surfaceBright = Color(0xFFFEF7FF)
private val md_theme_catppuccin_light_surfaceDim = Color(0xFFE0D7E5)
private val md_theme_catppuccin_light_surfaceContainer = Color(0xFFF4EBF9)
private val md_theme_catppuccin_light_surfaceContainerHigh = Color(0xFFEEE5F4)
private val md_theme_catppuccin_light_surfaceContainerHighest = Color(0xFFE9DFEE)
private val md_theme_catppuccin_light_surfaceContainerLow = Color(0xFFFAF0FF)
private val md_theme_catppuccin_light_surfaceContainerLowest = Color(0xFFFFFFFF)
private val md_theme_catppuccin_dark_primary = Color(0xFFF0E1FF)
private val md_theme_catppuccin_dark_onPrimary = Color(0xFF3A2657)
private val md_theme_catppuccin_dark_primaryContainer = Color(0xFFD9C0FB)
private val md_theme_catppuccin_dark_onPrimaryContainer = Color(0xFF604C7E)
private val md_theme_catppuccin_dark_inversePrimary = Color(0xFF695588)
private val md_theme_catppuccin_dark_secondary = Color(0xFFCEC2DB)
private val md_theme_catppuccin_dark_onSecondary = Color(0xFF352D41)
private val md_theme_catppuccin_dark_secondaryContainer = Color(0xFF4E455A)
private val md_theme_catppuccin_dark_onSecondaryContainer = Color(0xFFC0B4CD)
private val md_theme_catppuccin_dark_tertiary = Color(0xFFF2E996)
private val md_theme_catppuccin_dark_onTertiary = Color(0xFF353100)
private val md_theme_catppuccin_dark_tertiaryContainer = Color(0xFFD5CD7D)
private val md_theme_catppuccin_dark_onTertiaryContainer = Color(0xFF5C5713)
private val md_theme_catppuccin_dark_background = Color(0xFF11111B)
private val md_theme_catppuccin_dark_onBackground = Color(0xFFE7E1E6)
private val md_theme_catppuccin_dark_surface = Color(0xFF11111B)
private val md_theme_catppuccin_dark_onSurface = Color(0xFFE7E1E6)
private val md_theme_catppuccin_dark_surfaceVariant = Color(0xFF4A454E)
private val md_theme_catppuccin_dark_onSurfaceVariant = Color(0xFFCBC4CF)
private val md_theme_catppuccin_dark_surfaceTint = Color(0xFFD5BCF7)
private val md_theme_catppuccin_dark_inverseSurface = Color(0xFFE7E1E6)
private val md_theme_catppuccin_dark_inverseOnSurface = Color(0xFF322F33)
private val md_theme_catppuccin_dark_error = Color(0xFFFFB4AB)
private val md_theme_catppuccin_dark_onError = Color(0xFF690005)
private val md_theme_catppuccin_dark_errorContainer = Color(0xFF93000A)
private val md_theme_catppuccin_dark_onErrorContainer = Color(0xFFFFDAD6)
private val md_theme_catppuccin_dark_outline = Color(0xFF958E99)
private val md_theme_catppuccin_dark_outlineVariant = Color(0xFF4A454E)
private val md_theme_catppuccin_dark_scrim = Color(0xFF000000)
private val md_theme_catppuccin_dark_surfaceBright = Color(0xFF3B383C)
private val md_theme_catppuccin_dark_surfaceDim = Color(0xFF141316)
private val md_theme_catppuccin_dark_surfaceContainer = Color(0xFF211F22)
private val md_theme_catppuccin_dark_surfaceContainerHigh = Color(0xFF2B292D)
private val md_theme_catppuccin_dark_surfaceContainerHighest = Color(0xFF363438)
private val md_theme_catppuccin_dark_surfaceContainerLow = Color(0xFF1D1B1E)
private val md_theme_catppuccin_dark_surfaceContainerLowest = Color(0xFF0F0D11)

val EmberLightColors = lightColorScheme(
    primary = md_theme_ember_light_primary,
    onPrimary = md_theme_ember_light_onPrimary,
    primaryContainer = md_theme_ember_light_primaryContainer,
    onPrimaryContainer = md_theme_ember_light_onPrimaryContainer,
    inversePrimary = md_theme_ember_light_inversePrimary,
    secondary = md_theme_ember_light_secondary,
    onSecondary = md_theme_ember_light_onSecondary,
    secondaryContainer = md_theme_ember_light_secondaryContainer,
    onSecondaryContainer = md_theme_ember_light_onSecondaryContainer,
    tertiary = md_theme_ember_light_tertiary,
    onTertiary = md_theme_ember_light_onTertiary,
    tertiaryContainer = md_theme_ember_light_tertiaryContainer,
    onTertiaryContainer = md_theme_ember_light_onTertiaryContainer,
    background = md_theme_ember_light_background,
    onBackground = md_theme_ember_light_onBackground,
    surface = md_theme_ember_light_surface,
    onSurface = md_theme_ember_light_onSurface,
    surfaceVariant = md_theme_ember_light_surfaceVariant,
    onSurfaceVariant = md_theme_ember_light_onSurfaceVariant,
    surfaceTint = md_theme_ember_light_surfaceTint,
    inverseSurface = md_theme_ember_light_inverseSurface,
    inverseOnSurface = md_theme_ember_light_inverseOnSurface,
    error = md_theme_ember_light_error,
    onError = md_theme_ember_light_onError,
    errorContainer = md_theme_ember_light_errorContainer,
    onErrorContainer = md_theme_ember_light_onErrorContainer,
    outline = md_theme_ember_light_outline,
    outlineVariant = md_theme_ember_light_outlineVariant,
    scrim = md_theme_ember_light_scrim,
    surfaceBright = md_theme_ember_light_surfaceBright,
    surfaceDim = md_theme_ember_light_surfaceDim,
    surfaceContainer = md_theme_ember_light_surfaceContainer,
    surfaceContainerHigh = md_theme_ember_light_surfaceContainerHigh,
    surfaceContainerHighest = md_theme_ember_light_surfaceContainerHighest,
    surfaceContainerLow = md_theme_ember_light_surfaceContainerLow,
    surfaceContainerLowest = md_theme_ember_light_surfaceContainerLowest,
)

val EmberDarkColors = darkColorScheme(
    primary = md_theme_ember_dark_primary,
    onPrimary = md_theme_ember_dark_onPrimary,
    primaryContainer = md_theme_ember_dark_primaryContainer,
    onPrimaryContainer = md_theme_ember_dark_onPrimaryContainer,
    inversePrimary = md_theme_ember_dark_inversePrimary,
    secondary = md_theme_ember_dark_secondary,
    onSecondary = md_theme_ember_dark_onSecondary,
    secondaryContainer = md_theme_ember_dark_secondaryContainer,
    onSecondaryContainer = md_theme_ember_dark_onSecondaryContainer,
    tertiary = md_theme_ember_dark_tertiary,
    onTertiary = md_theme_ember_dark_onTertiary,
    tertiaryContainer = md_theme_ember_dark_tertiaryContainer,
    onTertiaryContainer = md_theme_ember_dark_onTertiaryContainer,
    background = md_theme_ember_dark_background,
    onBackground = md_theme_ember_dark_onBackground,
    surface = md_theme_ember_dark_surface,
    onSurface = md_theme_ember_dark_onSurface,
    surfaceVariant = md_theme_ember_dark_surfaceVariant,
    onSurfaceVariant = md_theme_ember_dark_onSurfaceVariant,
    surfaceTint = md_theme_ember_dark_surfaceTint,
    inverseSurface = md_theme_ember_dark_inverseSurface,
    inverseOnSurface = md_theme_ember_dark_inverseOnSurface,
    error = md_theme_ember_dark_error,
    onError = md_theme_ember_dark_onError,
    errorContainer = md_theme_ember_dark_errorContainer,
    onErrorContainer = md_theme_ember_dark_onErrorContainer,
    outline = md_theme_ember_dark_outline,
    outlineVariant = md_theme_ember_dark_outlineVariant,
    scrim = md_theme_ember_dark_scrim,
    surfaceBright = md_theme_ember_dark_surfaceBright,
    surfaceDim = md_theme_ember_dark_surfaceDim,
    surfaceContainer = md_theme_ember_dark_surfaceContainer,
    surfaceContainerHigh = md_theme_ember_dark_surfaceContainerHigh,
    surfaceContainerHighest = md_theme_ember_dark_surfaceContainerHighest,
    surfaceContainerLow = md_theme_ember_dark_surfaceContainerLow,
    surfaceContainerLowest = md_theme_ember_dark_surfaceContainerLowest,
)

val FernLightColors = lightColorScheme(
    primary = md_theme_fern_light_primary,
    onPrimary = md_theme_fern_light_onPrimary,
    primaryContainer = md_theme_fern_light_primaryContainer,
    onPrimaryContainer = md_theme_fern_light_onPrimaryContainer,
    inversePrimary = md_theme_fern_light_inversePrimary,
    secondary = md_theme_fern_light_secondary,
    onSecondary = md_theme_fern_light_onSecondary,
    secondaryContainer = md_theme_fern_light_secondaryContainer,
    onSecondaryContainer = md_theme_fern_light_onSecondaryContainer,
    tertiary = md_theme_fern_light_tertiary,
    onTertiary = md_theme_fern_light_onTertiary,
    tertiaryContainer = md_theme_fern_light_tertiaryContainer,
    onTertiaryContainer = md_theme_fern_light_onTertiaryContainer,
    background = md_theme_fern_light_background,
    onBackground = md_theme_fern_light_onBackground,
    surface = md_theme_fern_light_surface,
    onSurface = md_theme_fern_light_onSurface,
    surfaceVariant = md_theme_fern_light_surfaceVariant,
    onSurfaceVariant = md_theme_fern_light_onSurfaceVariant,
    surfaceTint = md_theme_fern_light_surfaceTint,
    inverseSurface = md_theme_fern_light_inverseSurface,
    inverseOnSurface = md_theme_fern_light_inverseOnSurface,
    error = md_theme_fern_light_error,
    onError = md_theme_fern_light_onError,
    errorContainer = md_theme_fern_light_errorContainer,
    onErrorContainer = md_theme_fern_light_onErrorContainer,
    outline = md_theme_fern_light_outline,
    outlineVariant = md_theme_fern_light_outlineVariant,
    scrim = md_theme_fern_light_scrim,
    surfaceBright = md_theme_fern_light_surfaceBright,
    surfaceDim = md_theme_fern_light_surfaceDim,
    surfaceContainer = md_theme_fern_light_surfaceContainer,
    surfaceContainerHigh = md_theme_fern_light_surfaceContainerHigh,
    surfaceContainerHighest = md_theme_fern_light_surfaceContainerHighest,
    surfaceContainerLow = md_theme_fern_light_surfaceContainerLow,
    surfaceContainerLowest = md_theme_fern_light_surfaceContainerLowest,
)

val FernDarkColors = darkColorScheme(
    primary = md_theme_fern_dark_primary,
    onPrimary = md_theme_fern_dark_onPrimary,
    primaryContainer = md_theme_fern_dark_primaryContainer,
    onPrimaryContainer = md_theme_fern_dark_onPrimaryContainer,
    inversePrimary = md_theme_fern_dark_inversePrimary,
    secondary = md_theme_fern_dark_secondary,
    onSecondary = md_theme_fern_dark_onSecondary,
    secondaryContainer = md_theme_fern_dark_secondaryContainer,
    onSecondaryContainer = md_theme_fern_dark_onSecondaryContainer,
    tertiary = md_theme_fern_dark_tertiary,
    onTertiary = md_theme_fern_dark_onTertiary,
    tertiaryContainer = md_theme_fern_dark_tertiaryContainer,
    onTertiaryContainer = md_theme_fern_dark_onTertiaryContainer,
    background = md_theme_fern_dark_background,
    onBackground = md_theme_fern_dark_onBackground,
    surface = md_theme_fern_dark_surface,
    onSurface = md_theme_fern_dark_onSurface,
    surfaceVariant = md_theme_fern_dark_surfaceVariant,
    onSurfaceVariant = md_theme_fern_dark_onSurfaceVariant,
    surfaceTint = md_theme_fern_dark_surfaceTint,
    inverseSurface = md_theme_fern_dark_inverseSurface,
    inverseOnSurface = md_theme_fern_dark_inverseOnSurface,
    error = md_theme_fern_dark_error,
    onError = md_theme_fern_dark_onError,
    errorContainer = md_theme_fern_dark_errorContainer,
    onErrorContainer = md_theme_fern_dark_onErrorContainer,
    outline = md_theme_fern_dark_outline,
    outlineVariant = md_theme_fern_dark_outlineVariant,
    scrim = md_theme_fern_dark_scrim,
    surfaceBright = md_theme_fern_dark_surfaceBright,
    surfaceDim = md_theme_fern_dark_surfaceDim,
    surfaceContainer = md_theme_fern_dark_surfaceContainer,
    surfaceContainerHigh = md_theme_fern_dark_surfaceContainerHigh,
    surfaceContainerHighest = md_theme_fern_dark_surfaceContainerHighest,
    surfaceContainerLow = md_theme_fern_dark_surfaceContainerLow,
    surfaceContainerLowest = md_theme_fern_dark_surfaceContainerLowest,
)

val MarineLightColors = lightColorScheme(
    primary = md_theme_marine_light_primary,
    onPrimary = md_theme_marine_light_onPrimary,
    primaryContainer = md_theme_marine_light_primaryContainer,
    onPrimaryContainer = md_theme_marine_light_onPrimaryContainer,
    inversePrimary = md_theme_marine_light_inversePrimary,
    secondary = md_theme_marine_light_secondary,
    onSecondary = md_theme_marine_light_onSecondary,
    secondaryContainer = md_theme_marine_light_secondaryContainer,
    onSecondaryContainer = md_theme_marine_light_onSecondaryContainer,
    tertiary = md_theme_marine_light_tertiary,
    onTertiary = md_theme_marine_light_onTertiary,
    tertiaryContainer = md_theme_marine_light_tertiaryContainer,
    onTertiaryContainer = md_theme_marine_light_onTertiaryContainer,
    background = md_theme_marine_light_background,
    onBackground = md_theme_marine_light_onBackground,
    surface = md_theme_marine_light_surface,
    onSurface = md_theme_marine_light_onSurface,
    surfaceVariant = md_theme_marine_light_surfaceVariant,
    onSurfaceVariant = md_theme_marine_light_onSurfaceVariant,
    surfaceTint = md_theme_marine_light_surfaceTint,
    inverseSurface = md_theme_marine_light_inverseSurface,
    inverseOnSurface = md_theme_marine_light_inverseOnSurface,
    error = md_theme_marine_light_error,
    onError = md_theme_marine_light_onError,
    errorContainer = md_theme_marine_light_errorContainer,
    onErrorContainer = md_theme_marine_light_onErrorContainer,
    outline = md_theme_marine_light_outline,
    outlineVariant = md_theme_marine_light_outlineVariant,
    scrim = md_theme_marine_light_scrim,
    surfaceBright = md_theme_marine_light_surfaceBright,
    surfaceDim = md_theme_marine_light_surfaceDim,
    surfaceContainer = md_theme_marine_light_surfaceContainer,
    surfaceContainerHigh = md_theme_marine_light_surfaceContainerHigh,
    surfaceContainerHighest = md_theme_marine_light_surfaceContainerHighest,
    surfaceContainerLow = md_theme_marine_light_surfaceContainerLow,
    surfaceContainerLowest = md_theme_marine_light_surfaceContainerLowest,
)

val MarineDarkColors = darkColorScheme(
    primary = md_theme_marine_dark_primary,
    onPrimary = md_theme_marine_dark_onPrimary,
    primaryContainer = md_theme_marine_dark_primaryContainer,
    onPrimaryContainer = md_theme_marine_dark_onPrimaryContainer,
    inversePrimary = md_theme_marine_dark_inversePrimary,
    secondary = md_theme_marine_dark_secondary,
    onSecondary = md_theme_marine_dark_onSecondary,
    secondaryContainer = md_theme_marine_dark_secondaryContainer,
    onSecondaryContainer = md_theme_marine_dark_onSecondaryContainer,
    tertiary = md_theme_marine_dark_tertiary,
    onTertiary = md_theme_marine_dark_onTertiary,
    tertiaryContainer = md_theme_marine_dark_tertiaryContainer,
    onTertiaryContainer = md_theme_marine_dark_onTertiaryContainer,
    background = md_theme_marine_dark_background,
    onBackground = md_theme_marine_dark_onBackground,
    surface = md_theme_marine_dark_surface,
    onSurface = md_theme_marine_dark_onSurface,
    surfaceVariant = md_theme_marine_dark_surfaceVariant,
    onSurfaceVariant = md_theme_marine_dark_onSurfaceVariant,
    surfaceTint = md_theme_marine_dark_surfaceTint,
    inverseSurface = md_theme_marine_dark_inverseSurface,
    inverseOnSurface = md_theme_marine_dark_inverseOnSurface,
    error = md_theme_marine_dark_error,
    onError = md_theme_marine_dark_onError,
    errorContainer = md_theme_marine_dark_errorContainer,
    onErrorContainer = md_theme_marine_dark_onErrorContainer,
    outline = md_theme_marine_dark_outline,
    outlineVariant = md_theme_marine_dark_outlineVariant,
    scrim = md_theme_marine_dark_scrim,
    surfaceBright = md_theme_marine_dark_surfaceBright,
    surfaceDim = md_theme_marine_dark_surfaceDim,
    surfaceContainer = md_theme_marine_dark_surfaceContainer,
    surfaceContainerHigh = md_theme_marine_dark_surfaceContainerHigh,
    surfaceContainerHighest = md_theme_marine_dark_surfaceContainerHighest,
    surfaceContainerLow = md_theme_marine_dark_surfaceContainerLow,
    surfaceContainerLowest = md_theme_marine_dark_surfaceContainerLowest,
)

val OliveLightColors = lightColorScheme(
    primary = md_theme_olive_light_primary,
    onPrimary = md_theme_olive_light_onPrimary,
    primaryContainer = md_theme_olive_light_primaryContainer,
    onPrimaryContainer = md_theme_olive_light_onPrimaryContainer,
    inversePrimary = md_theme_olive_light_inversePrimary,
    secondary = md_theme_olive_light_secondary,
    onSecondary = md_theme_olive_light_onSecondary,
    secondaryContainer = md_theme_olive_light_secondaryContainer,
    onSecondaryContainer = md_theme_olive_light_onSecondaryContainer,
    tertiary = md_theme_olive_light_tertiary,
    onTertiary = md_theme_olive_light_onTertiary,
    tertiaryContainer = md_theme_olive_light_tertiaryContainer,
    onTertiaryContainer = md_theme_olive_light_onTertiaryContainer,
    background = md_theme_olive_light_background,
    onBackground = md_theme_olive_light_onBackground,
    surface = md_theme_olive_light_surface,
    onSurface = md_theme_olive_light_onSurface,
    surfaceVariant = md_theme_olive_light_surfaceVariant,
    onSurfaceVariant = md_theme_olive_light_onSurfaceVariant,
    surfaceTint = md_theme_olive_light_surfaceTint,
    inverseSurface = md_theme_olive_light_inverseSurface,
    inverseOnSurface = md_theme_olive_light_inverseOnSurface,
    error = md_theme_olive_light_error,
    onError = md_theme_olive_light_onError,
    errorContainer = md_theme_olive_light_errorContainer,
    onErrorContainer = md_theme_olive_light_onErrorContainer,
    outline = md_theme_olive_light_outline,
    outlineVariant = md_theme_olive_light_outlineVariant,
    scrim = md_theme_olive_light_scrim,
    surfaceBright = md_theme_olive_light_surfaceBright,
    surfaceDim = md_theme_olive_light_surfaceDim,
    surfaceContainer = md_theme_olive_light_surfaceContainer,
    surfaceContainerHigh = md_theme_olive_light_surfaceContainerHigh,
    surfaceContainerHighest = md_theme_olive_light_surfaceContainerHighest,
    surfaceContainerLow = md_theme_olive_light_surfaceContainerLow,
    surfaceContainerLowest = md_theme_olive_light_surfaceContainerLowest,
)

val OliveDarkColors = darkColorScheme(
    primary = md_theme_olive_dark_primary,
    onPrimary = md_theme_olive_dark_onPrimary,
    primaryContainer = md_theme_olive_dark_primaryContainer,
    onPrimaryContainer = md_theme_olive_dark_onPrimaryContainer,
    inversePrimary = md_theme_olive_dark_inversePrimary,
    secondary = md_theme_olive_dark_secondary,
    onSecondary = md_theme_olive_dark_onSecondary,
    secondaryContainer = md_theme_olive_dark_secondaryContainer,
    onSecondaryContainer = md_theme_olive_dark_onSecondaryContainer,
    tertiary = md_theme_olive_dark_tertiary,
    onTertiary = md_theme_olive_dark_onTertiary,
    tertiaryContainer = md_theme_olive_dark_tertiaryContainer,
    onTertiaryContainer = md_theme_olive_dark_onTertiaryContainer,
    background = md_theme_olive_dark_background,
    onBackground = md_theme_olive_dark_onBackground,
    surface = md_theme_olive_dark_surface,
    onSurface = md_theme_olive_dark_onSurface,
    surfaceVariant = md_theme_olive_dark_surfaceVariant,
    onSurfaceVariant = md_theme_olive_dark_onSurfaceVariant,
    surfaceTint = md_theme_olive_dark_surfaceTint,
    inverseSurface = md_theme_olive_dark_inverseSurface,
    inverseOnSurface = md_theme_olive_dark_inverseOnSurface,
    error = md_theme_olive_dark_error,
    onError = md_theme_olive_dark_onError,
    errorContainer = md_theme_olive_dark_errorContainer,
    onErrorContainer = md_theme_olive_dark_onErrorContainer,
    outline = md_theme_olive_dark_outline,
    outlineVariant = md_theme_olive_dark_outlineVariant,
    scrim = md_theme_olive_dark_scrim,
    surfaceBright = md_theme_olive_dark_surfaceBright,
    surfaceDim = md_theme_olive_dark_surfaceDim,
    surfaceContainer = md_theme_olive_dark_surfaceContainer,
    surfaceContainerHigh = md_theme_olive_dark_surfaceContainerHigh,
    surfaceContainerHighest = md_theme_olive_dark_surfaceContainerHighest,
    surfaceContainerLow = md_theme_olive_dark_surfaceContainerLow,
    surfaceContainerLowest = md_theme_olive_dark_surfaceContainerLowest,
)

val LavenderLightColors = lightColorScheme(
    primary = md_theme_lavender_light_primary,
    onPrimary = md_theme_lavender_light_onPrimary,
    primaryContainer = md_theme_lavender_light_primaryContainer,
    onPrimaryContainer = md_theme_lavender_light_onPrimaryContainer,
    inversePrimary = md_theme_lavender_light_inversePrimary,
    secondary = md_theme_lavender_light_secondary,
    onSecondary = md_theme_lavender_light_onSecondary,
    secondaryContainer = md_theme_lavender_light_secondaryContainer,
    onSecondaryContainer = md_theme_lavender_light_onSecondaryContainer,
    tertiary = md_theme_lavender_light_tertiary,
    onTertiary = md_theme_lavender_light_onTertiary,
    tertiaryContainer = md_theme_lavender_light_tertiaryContainer,
    onTertiaryContainer = md_theme_lavender_light_onTertiaryContainer,
    background = md_theme_lavender_light_background,
    onBackground = md_theme_lavender_light_onBackground,
    surface = md_theme_lavender_light_surface,
    onSurface = md_theme_lavender_light_onSurface,
    surfaceVariant = md_theme_lavender_light_surfaceVariant,
    onSurfaceVariant = md_theme_lavender_light_onSurfaceVariant,
    surfaceTint = md_theme_lavender_light_surfaceTint,
    inverseSurface = md_theme_lavender_light_inverseSurface,
    inverseOnSurface = md_theme_lavender_light_inverseOnSurface,
    error = md_theme_lavender_light_error,
    onError = md_theme_lavender_light_onError,
    errorContainer = md_theme_lavender_light_errorContainer,
    onErrorContainer = md_theme_lavender_light_onErrorContainer,
    outline = md_theme_lavender_light_outline,
    outlineVariant = md_theme_lavender_light_outlineVariant,
    scrim = md_theme_lavender_light_scrim,
    surfaceBright = md_theme_lavender_light_surfaceBright,
    surfaceDim = md_theme_lavender_light_surfaceDim,
    surfaceContainer = md_theme_lavender_light_surfaceContainer,
    surfaceContainerHigh = md_theme_lavender_light_surfaceContainerHigh,
    surfaceContainerHighest = md_theme_lavender_light_surfaceContainerHighest,
    surfaceContainerLow = md_theme_lavender_light_surfaceContainerLow,
    surfaceContainerLowest = md_theme_lavender_light_surfaceContainerLowest,
)

val LavenderDarkColors = darkColorScheme(
    primary = md_theme_lavender_dark_primary,
    onPrimary = md_theme_lavender_dark_onPrimary,
    primaryContainer = md_theme_lavender_dark_primaryContainer,
    onPrimaryContainer = md_theme_lavender_dark_onPrimaryContainer,
    inversePrimary = md_theme_lavender_dark_inversePrimary,
    secondary = md_theme_lavender_dark_secondary,
    onSecondary = md_theme_lavender_dark_onSecondary,
    secondaryContainer = md_theme_lavender_dark_secondaryContainer,
    onSecondaryContainer = md_theme_lavender_dark_onSecondaryContainer,
    tertiary = md_theme_lavender_dark_tertiary,
    onTertiary = md_theme_lavender_dark_onTertiary,
    tertiaryContainer = md_theme_lavender_dark_tertiaryContainer,
    onTertiaryContainer = md_theme_lavender_dark_onTertiaryContainer,
    background = md_theme_lavender_dark_background,
    onBackground = md_theme_lavender_dark_onBackground,
    surface = md_theme_lavender_dark_surface,
    onSurface = md_theme_lavender_dark_onSurface,
    surfaceVariant = md_theme_lavender_dark_surfaceVariant,
    onSurfaceVariant = md_theme_lavender_dark_onSurfaceVariant,
    surfaceTint = md_theme_lavender_dark_surfaceTint,
    inverseSurface = md_theme_lavender_dark_inverseSurface,
    inverseOnSurface = md_theme_lavender_dark_inverseOnSurface,
    error = md_theme_lavender_dark_error,
    onError = md_theme_lavender_dark_onError,
    errorContainer = md_theme_lavender_dark_errorContainer,
    onErrorContainer = md_theme_lavender_dark_onErrorContainer,
    outline = md_theme_lavender_dark_outline,
    outlineVariant = md_theme_lavender_dark_outlineVariant,
    scrim = md_theme_lavender_dark_scrim,
    surfaceBright = md_theme_lavender_dark_surfaceBright,
    surfaceDim = md_theme_lavender_dark_surfaceDim,
    surfaceContainer = md_theme_lavender_dark_surfaceContainer,
    surfaceContainerHigh = md_theme_lavender_dark_surfaceContainerHigh,
    surfaceContainerHighest = md_theme_lavender_dark_surfaceContainerHighest,
    surfaceContainerLow = md_theme_lavender_dark_surfaceContainerLow,
    surfaceContainerLowest = md_theme_lavender_dark_surfaceContainerLowest,
)

val SakuraLightColors = lightColorScheme(
    primary = md_theme_sakura_light_primary,
    onPrimary = md_theme_sakura_light_onPrimary,
    primaryContainer = md_theme_sakura_light_primaryContainer,
    onPrimaryContainer = md_theme_sakura_light_onPrimaryContainer,
    inversePrimary = md_theme_sakura_light_inversePrimary,
    secondary = md_theme_sakura_light_secondary,
    onSecondary = md_theme_sakura_light_onSecondary,
    secondaryContainer = md_theme_sakura_light_secondaryContainer,
    onSecondaryContainer = md_theme_sakura_light_onSecondaryContainer,
    tertiary = md_theme_sakura_light_tertiary,
    onTertiary = md_theme_sakura_light_onTertiary,
    tertiaryContainer = md_theme_sakura_light_tertiaryContainer,
    onTertiaryContainer = md_theme_sakura_light_onTertiaryContainer,
    background = md_theme_sakura_light_background,
    onBackground = md_theme_sakura_light_onBackground,
    surface = md_theme_sakura_light_surface,
    onSurface = md_theme_sakura_light_onSurface,
    surfaceVariant = md_theme_sakura_light_surfaceVariant,
    onSurfaceVariant = md_theme_sakura_light_onSurfaceVariant,
    surfaceTint = md_theme_sakura_light_surfaceTint,
    inverseSurface = md_theme_sakura_light_inverseSurface,
    inverseOnSurface = md_theme_sakura_light_inverseOnSurface,
    error = md_theme_sakura_light_error,
    onError = md_theme_sakura_light_onError,
    errorContainer = md_theme_sakura_light_errorContainer,
    onErrorContainer = md_theme_sakura_light_onErrorContainer,
    outline = md_theme_sakura_light_outline,
    outlineVariant = md_theme_sakura_light_outlineVariant,
    scrim = md_theme_sakura_light_scrim,
    surfaceBright = md_theme_sakura_light_surfaceBright,
    surfaceDim = md_theme_sakura_light_surfaceDim,
    surfaceContainer = md_theme_sakura_light_surfaceContainer,
    surfaceContainerHigh = md_theme_sakura_light_surfaceContainerHigh,
    surfaceContainerHighest = md_theme_sakura_light_surfaceContainerHighest,
    surfaceContainerLow = md_theme_sakura_light_surfaceContainerLow,
    surfaceContainerLowest = md_theme_sakura_light_surfaceContainerLowest,
)

val SakuraDarkColors = darkColorScheme(
    primary = md_theme_sakura_dark_primary,
    onPrimary = md_theme_sakura_dark_onPrimary,
    primaryContainer = md_theme_sakura_dark_primaryContainer,
    onPrimaryContainer = md_theme_sakura_dark_onPrimaryContainer,
    inversePrimary = md_theme_sakura_dark_inversePrimary,
    secondary = md_theme_sakura_dark_secondary,
    onSecondary = md_theme_sakura_dark_onSecondary,
    secondaryContainer = md_theme_sakura_dark_secondaryContainer,
    onSecondaryContainer = md_theme_sakura_dark_onSecondaryContainer,
    tertiary = md_theme_sakura_dark_tertiary,
    onTertiary = md_theme_sakura_dark_onTertiary,
    tertiaryContainer = md_theme_sakura_dark_tertiaryContainer,
    onTertiaryContainer = md_theme_sakura_dark_onTertiaryContainer,
    background = md_theme_sakura_dark_background,
    onBackground = md_theme_sakura_dark_onBackground,
    surface = md_theme_sakura_dark_surface,
    onSurface = md_theme_sakura_dark_onSurface,
    surfaceVariant = md_theme_sakura_dark_surfaceVariant,
    onSurfaceVariant = md_theme_sakura_dark_onSurfaceVariant,
    surfaceTint = md_theme_sakura_dark_surfaceTint,
    inverseSurface = md_theme_sakura_dark_inverseSurface,
    inverseOnSurface = md_theme_sakura_dark_inverseOnSurface,
    error = md_theme_sakura_dark_error,
    onError = md_theme_sakura_dark_onError,
    errorContainer = md_theme_sakura_dark_errorContainer,
    onErrorContainer = md_theme_sakura_dark_onErrorContainer,
    outline = md_theme_sakura_dark_outline,
    outlineVariant = md_theme_sakura_dark_outlineVariant,
    scrim = md_theme_sakura_dark_scrim,
    surfaceBright = md_theme_sakura_dark_surfaceBright,
    surfaceDim = md_theme_sakura_dark_surfaceDim,
    surfaceContainer = md_theme_sakura_dark_surfaceContainer,
    surfaceContainerHigh = md_theme_sakura_dark_surfaceContainerHigh,
    surfaceContainerHighest = md_theme_sakura_dark_surfaceContainerHighest,
    surfaceContainerLow = md_theme_sakura_dark_surfaceContainerLow,
    surfaceContainerLowest = md_theme_sakura_dark_surfaceContainerLowest,
)

val SolarizedLightColors = lightColorScheme(
    primary = md_theme_solarized_light_primary,
    onPrimary = md_theme_solarized_light_onPrimary,
    primaryContainer = md_theme_solarized_light_primaryContainer,
    onPrimaryContainer = md_theme_solarized_light_onPrimaryContainer,
    inversePrimary = md_theme_solarized_light_inversePrimary,
    secondary = md_theme_solarized_light_secondary,
    onSecondary = md_theme_solarized_light_onSecondary,
    secondaryContainer = md_theme_solarized_light_secondaryContainer,
    onSecondaryContainer = md_theme_solarized_light_onSecondaryContainer,
    tertiary = md_theme_solarized_light_tertiary,
    onTertiary = md_theme_solarized_light_onTertiary,
    tertiaryContainer = md_theme_solarized_light_tertiaryContainer,
    onTertiaryContainer = md_theme_solarized_light_onTertiaryContainer,
    background = md_theme_solarized_light_background,
    onBackground = md_theme_solarized_light_onBackground,
    surface = md_theme_solarized_light_surface,
    onSurface = md_theme_solarized_light_onSurface,
    surfaceVariant = md_theme_solarized_light_surfaceVariant,
    onSurfaceVariant = md_theme_solarized_light_onSurfaceVariant,
    surfaceTint = md_theme_solarized_light_surfaceTint,
    inverseSurface = md_theme_solarized_light_inverseSurface,
    inverseOnSurface = md_theme_solarized_light_inverseOnSurface,
    error = md_theme_solarized_light_error,
    onError = md_theme_solarized_light_onError,
    errorContainer = md_theme_solarized_light_errorContainer,
    onErrorContainer = md_theme_solarized_light_onErrorContainer,
    outline = md_theme_solarized_light_outline,
    outlineVariant = md_theme_solarized_light_outlineVariant,
    scrim = md_theme_solarized_light_scrim,
    surfaceBright = md_theme_solarized_light_surfaceBright,
    surfaceDim = md_theme_solarized_light_surfaceDim,
    surfaceContainer = md_theme_solarized_light_surfaceContainer,
    surfaceContainerHigh = md_theme_solarized_light_surfaceContainerHigh,
    surfaceContainerHighest = md_theme_solarized_light_surfaceContainerHighest,
    surfaceContainerLow = md_theme_solarized_light_surfaceContainerLow,
    surfaceContainerLowest = md_theme_solarized_light_surfaceContainerLowest,
)

val SolarizedDarkColors = darkColorScheme(
    primary = md_theme_solarized_dark_primary,
    onPrimary = md_theme_solarized_dark_onPrimary,
    primaryContainer = md_theme_solarized_dark_primaryContainer,
    onPrimaryContainer = md_theme_solarized_dark_onPrimaryContainer,
    inversePrimary = md_theme_solarized_dark_inversePrimary,
    secondary = md_theme_solarized_dark_secondary,
    onSecondary = md_theme_solarized_dark_onSecondary,
    secondaryContainer = md_theme_solarized_dark_secondaryContainer,
    onSecondaryContainer = md_theme_solarized_dark_onSecondaryContainer,
    tertiary = md_theme_solarized_dark_tertiary,
    onTertiary = md_theme_solarized_dark_onTertiary,
    tertiaryContainer = md_theme_solarized_dark_tertiaryContainer,
    onTertiaryContainer = md_theme_solarized_dark_onTertiaryContainer,
    background = md_theme_solarized_dark_background,
    onBackground = md_theme_solarized_dark_onBackground,
    surface = md_theme_solarized_dark_surface,
    onSurface = md_theme_solarized_dark_onSurface,
    surfaceVariant = md_theme_solarized_dark_surfaceVariant,
    onSurfaceVariant = md_theme_solarized_dark_onSurfaceVariant,
    surfaceTint = md_theme_solarized_dark_surfaceTint,
    inverseSurface = md_theme_solarized_dark_inverseSurface,
    inverseOnSurface = md_theme_solarized_dark_inverseOnSurface,
    error = md_theme_solarized_dark_error,
    onError = md_theme_solarized_dark_onError,
    errorContainer = md_theme_solarized_dark_errorContainer,
    onErrorContainer = md_theme_solarized_dark_onErrorContainer,
    outline = md_theme_solarized_dark_outline,
    outlineVariant = md_theme_solarized_dark_outlineVariant,
    scrim = md_theme_solarized_dark_scrim,
    surfaceBright = md_theme_solarized_dark_surfaceBright,
    surfaceDim = md_theme_solarized_dark_surfaceDim,
    surfaceContainer = md_theme_solarized_dark_surfaceContainer,
    surfaceContainerHigh = md_theme_solarized_dark_surfaceContainerHigh,
    surfaceContainerHighest = md_theme_solarized_dark_surfaceContainerHighest,
    surfaceContainerLow = md_theme_solarized_dark_surfaceContainerLow,
    surfaceContainerLowest = md_theme_solarized_dark_surfaceContainerLowest,
)

val NordLightColors = lightColorScheme(
    primary = md_theme_nord_light_primary,
    onPrimary = md_theme_nord_light_onPrimary,
    primaryContainer = md_theme_nord_light_primaryContainer,
    onPrimaryContainer = md_theme_nord_light_onPrimaryContainer,
    inversePrimary = md_theme_nord_light_inversePrimary,
    secondary = md_theme_nord_light_secondary,
    onSecondary = md_theme_nord_light_onSecondary,
    secondaryContainer = md_theme_nord_light_secondaryContainer,
    onSecondaryContainer = md_theme_nord_light_onSecondaryContainer,
    tertiary = md_theme_nord_light_tertiary,
    onTertiary = md_theme_nord_light_onTertiary,
    tertiaryContainer = md_theme_nord_light_tertiaryContainer,
    onTertiaryContainer = md_theme_nord_light_onTertiaryContainer,
    background = md_theme_nord_light_background,
    onBackground = md_theme_nord_light_onBackground,
    surface = md_theme_nord_light_surface,
    onSurface = md_theme_nord_light_onSurface,
    surfaceVariant = md_theme_nord_light_surfaceVariant,
    onSurfaceVariant = md_theme_nord_light_onSurfaceVariant,
    surfaceTint = md_theme_nord_light_surfaceTint,
    inverseSurface = md_theme_nord_light_inverseSurface,
    inverseOnSurface = md_theme_nord_light_inverseOnSurface,
    error = md_theme_nord_light_error,
    onError = md_theme_nord_light_onError,
    errorContainer = md_theme_nord_light_errorContainer,
    onErrorContainer = md_theme_nord_light_onErrorContainer,
    outline = md_theme_nord_light_outline,
    outlineVariant = md_theme_nord_light_outlineVariant,
    scrim = md_theme_nord_light_scrim,
    surfaceBright = md_theme_nord_light_surfaceBright,
    surfaceDim = md_theme_nord_light_surfaceDim,
    surfaceContainer = md_theme_nord_light_surfaceContainer,
    surfaceContainerHigh = md_theme_nord_light_surfaceContainerHigh,
    surfaceContainerHighest = md_theme_nord_light_surfaceContainerHighest,
    surfaceContainerLow = md_theme_nord_light_surfaceContainerLow,
    surfaceContainerLowest = md_theme_nord_light_surfaceContainerLowest,
)

val NordDarkColors = darkColorScheme(
    primary = md_theme_nord_dark_primary,
    onPrimary = md_theme_nord_dark_onPrimary,
    primaryContainer = md_theme_nord_dark_primaryContainer,
    onPrimaryContainer = md_theme_nord_dark_onPrimaryContainer,
    inversePrimary = md_theme_nord_dark_inversePrimary,
    secondary = md_theme_nord_dark_secondary,
    onSecondary = md_theme_nord_dark_onSecondary,
    secondaryContainer = md_theme_nord_dark_secondaryContainer,
    onSecondaryContainer = md_theme_nord_dark_onSecondaryContainer,
    tertiary = md_theme_nord_dark_tertiary,
    onTertiary = md_theme_nord_dark_onTertiary,
    tertiaryContainer = md_theme_nord_dark_tertiaryContainer,
    onTertiaryContainer = md_theme_nord_dark_onTertiaryContainer,
    background = md_theme_nord_dark_background,
    onBackground = md_theme_nord_dark_onBackground,
    surface = md_theme_nord_dark_surface,
    onSurface = md_theme_nord_dark_onSurface,
    surfaceVariant = md_theme_nord_dark_surfaceVariant,
    onSurfaceVariant = md_theme_nord_dark_onSurfaceVariant,
    surfaceTint = md_theme_nord_dark_surfaceTint,
    inverseSurface = md_theme_nord_dark_inverseSurface,
    inverseOnSurface = md_theme_nord_dark_inverseOnSurface,
    error = md_theme_nord_dark_error,
    onError = md_theme_nord_dark_onError,
    errorContainer = md_theme_nord_dark_errorContainer,
    onErrorContainer = md_theme_nord_dark_onErrorContainer,
    outline = md_theme_nord_dark_outline,
    outlineVariant = md_theme_nord_dark_outlineVariant,
    scrim = md_theme_nord_dark_scrim,
    surfaceBright = md_theme_nord_dark_surfaceBright,
    surfaceDim = md_theme_nord_dark_surfaceDim,
    surfaceContainer = md_theme_nord_dark_surfaceContainer,
    surfaceContainerHigh = md_theme_nord_dark_surfaceContainerHigh,
    surfaceContainerHighest = md_theme_nord_dark_surfaceContainerHighest,
    surfaceContainerLow = md_theme_nord_dark_surfaceContainerLow,
    surfaceContainerLowest = md_theme_nord_dark_surfaceContainerLowest,
)

val CatppuccinLightColors = lightColorScheme(
    primary = md_theme_catppuccin_light_primary,
    onPrimary = md_theme_catppuccin_light_onPrimary,
    primaryContainer = md_theme_catppuccin_light_primaryContainer,
    onPrimaryContainer = md_theme_catppuccin_light_onPrimaryContainer,
    inversePrimary = md_theme_catppuccin_light_inversePrimary,
    secondary = md_theme_catppuccin_light_secondary,
    onSecondary = md_theme_catppuccin_light_onSecondary,
    secondaryContainer = md_theme_catppuccin_light_secondaryContainer,
    onSecondaryContainer = md_theme_catppuccin_light_onSecondaryContainer,
    tertiary = md_theme_catppuccin_light_tertiary,
    onTertiary = md_theme_catppuccin_light_onTertiary,
    tertiaryContainer = md_theme_catppuccin_light_tertiaryContainer,
    onTertiaryContainer = md_theme_catppuccin_light_onTertiaryContainer,
    background = md_theme_catppuccin_light_background,
    onBackground = md_theme_catppuccin_light_onBackground,
    surface = md_theme_catppuccin_light_surface,
    onSurface = md_theme_catppuccin_light_onSurface,
    surfaceVariant = md_theme_catppuccin_light_surfaceVariant,
    onSurfaceVariant = md_theme_catppuccin_light_onSurfaceVariant,
    surfaceTint = md_theme_catppuccin_light_surfaceTint,
    inverseSurface = md_theme_catppuccin_light_inverseSurface,
    inverseOnSurface = md_theme_catppuccin_light_inverseOnSurface,
    error = md_theme_catppuccin_light_error,
    onError = md_theme_catppuccin_light_onError,
    errorContainer = md_theme_catppuccin_light_errorContainer,
    onErrorContainer = md_theme_catppuccin_light_onErrorContainer,
    outline = md_theme_catppuccin_light_outline,
    outlineVariant = md_theme_catppuccin_light_outlineVariant,
    scrim = md_theme_catppuccin_light_scrim,
    surfaceBright = md_theme_catppuccin_light_surfaceBright,
    surfaceDim = md_theme_catppuccin_light_surfaceDim,
    surfaceContainer = md_theme_catppuccin_light_surfaceContainer,
    surfaceContainerHigh = md_theme_catppuccin_light_surfaceContainerHigh,
    surfaceContainerHighest = md_theme_catppuccin_light_surfaceContainerHighest,
    surfaceContainerLow = md_theme_catppuccin_light_surfaceContainerLow,
    surfaceContainerLowest = md_theme_catppuccin_light_surfaceContainerLowest,
)

val CatppuccinDarkColors = darkColorScheme(
    primary = md_theme_catppuccin_dark_primary,
    onPrimary = md_theme_catppuccin_dark_onPrimary,
    primaryContainer = md_theme_catppuccin_dark_primaryContainer,
    onPrimaryContainer = md_theme_catppuccin_dark_onPrimaryContainer,
    inversePrimary = md_theme_catppuccin_dark_inversePrimary,
    secondary = md_theme_catppuccin_dark_secondary,
    onSecondary = md_theme_catppuccin_dark_onSecondary,
    secondaryContainer = md_theme_catppuccin_dark_secondaryContainer,
    onSecondaryContainer = md_theme_catppuccin_dark_onSecondaryContainer,
    tertiary = md_theme_catppuccin_dark_tertiary,
    onTertiary = md_theme_catppuccin_dark_onTertiary,
    tertiaryContainer = md_theme_catppuccin_dark_tertiaryContainer,
    onTertiaryContainer = md_theme_catppuccin_dark_onTertiaryContainer,
    background = md_theme_catppuccin_dark_background,
    onBackground = md_theme_catppuccin_dark_onBackground,
    surface = md_theme_catppuccin_dark_surface,
    onSurface = md_theme_catppuccin_dark_onSurface,
    surfaceVariant = md_theme_catppuccin_dark_surfaceVariant,
    onSurfaceVariant = md_theme_catppuccin_dark_onSurfaceVariant,
    surfaceTint = md_theme_catppuccin_dark_surfaceTint,
    inverseSurface = md_theme_catppuccin_dark_inverseSurface,
    inverseOnSurface = md_theme_catppuccin_dark_inverseOnSurface,
    error = md_theme_catppuccin_dark_error,
    onError = md_theme_catppuccin_dark_onError,
    errorContainer = md_theme_catppuccin_dark_errorContainer,
    onErrorContainer = md_theme_catppuccin_dark_onErrorContainer,
    outline = md_theme_catppuccin_dark_outline,
    outlineVariant = md_theme_catppuccin_dark_outlineVariant,
    scrim = md_theme_catppuccin_dark_scrim,
    surfaceBright = md_theme_catppuccin_dark_surfaceBright,
    surfaceDim = md_theme_catppuccin_dark_surfaceDim,
    surfaceContainer = md_theme_catppuccin_dark_surfaceContainer,
    surfaceContainerHigh = md_theme_catppuccin_dark_surfaceContainerHigh,
    surfaceContainerHighest = md_theme_catppuccin_dark_surfaceContainerHighest,
    surfaceContainerLow = md_theme_catppuccin_dark_surfaceContainerLow,
    surfaceContainerLowest = md_theme_catppuccin_dark_surfaceContainerLowest,
)
